In [1]:
import pandas as pd

df = pd.read_csv("../data/twcs.csv")

In [2]:
df.shape

(2811774, 7)

In [3]:
df.head()

,tweet_id,author_id,inbound,created_at,text,response_tweet_id,in_response_to_tweet_id
0,1,sprintcare,False,Tue Oct 31 22:10:47 +0000 2017,@115712 I understand. I would like to assist y...,2,3.0
1,2,115712,True,Tue Oct 31 22:11:45 +0000 2017,@sprintcare and how do you propose we do that,NaN,1.0
2,3,115712,True,Tue Oct 31 22:08:27 +0000 2017,@sprintcare I have sent several private messag...,1,4.0
3,4,sprintcare,False,Tue Oct 31 21:54:49 +0000 2017,@115712 Please send us a Private Message so th...,3,5.0
4,5,115712,True,Tue Oct 31 21:49:35 +0000 2017,@sprintcare I did.,4,6.0

In [4]:
df.columns

Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='str')

In [5]:
df["inbound"].value_counts()

inbound
True     1537843
False    1273931
Name: count, dtype: int64

In [6]:
brand_counts = (
    df[df["inbound"] == False]["author_id"]
    .value_counts()
)

brand_counts.head(20)

author_id
AmazonHelp         169840
AppleSupport       106860
Uber_Support        56270
SpotifyCares        43265
Delta               42253
Tesco               38573
AmericanAir         36764
TMobileHelp         34317
comcastcares        33031
British_Airways     29361
SouthwestAir        28977
VirginTrains        27817
Ask_Spectrum        25860
XboxSupport         24557
sprintcare          22381
hulu_support        21872
sainsburys          19466
GWRHelp             19364
AskPlayStation      19098
ChipotleTweets      18749
Name: count, dtype: int64

In [7]:
brand_counts.head(20).to_frame("outbound_tweets")

                 outbound_tweets
author_id
AmazonHelp                169840
AppleSupport              106860
Uber_Support               56270
SpotifyCares               43265
Delta                      42253
Tesco                      38573
AmericanAir                36764
TMobileHelp                34317
comcastcares               33031
British_Airways            29361
SouthwestAir               28977
VirginTrains               27817
Ask_Spectrum               25860
XboxSupport                24557
sprintcare                 22381
hulu_support               21872
sainsburys                 19466
GWRHelp                    19364
AskPlayStation             19098
ChipotleTweets             18749

In [9]:
amazon = df[df["author_id"] == "AmazonHelp"]

amazon[["tweet_id", "inbound", "text", 
        "response_tweet_id", "in_response_to_tweet_id"]].head(20)

,tweet_id,inbound,text,response_tweet_id,in_response_to_tweet_id
181,269,False,@115770 こんにちは、アマゾン公式です。Fire TV Stickが見れないというのは...,"270,271",272.0
184,273,False,@115770 カスタマーサービスにてお問い合わせ済みとのことで、お手数をおかけいたしました...,274,271.0
186,275,False,@115770 恐れ入ります。至らない点も多々あるかとは存じますが、今後ともどうぞよろしくお...,NaN,274.0
234,324,False,@115792 ご不便をおかけしております。アプリをご利用でしょうか。強制停止&gt;端末の...,NaN,325.0
321,615,False,@115820 I'm sorry we've let you down! Without ...,616,617.0
323,618,False,@115820 We'd like to take a further look into ...,619,616.0
326,620,False,@115822 I am unable to affect your account via...,NaN,621.0
328,622,False,"@115824 Hi, wir erhalten die Filme/Serien so v...",623,624.0
330,625,False,@115824 Wir haben zu danken. Schönen Abend noc...,NaN,623.0
332,626,False,@115826 I'm sorry for the wait. You'll receive...,627,628.0
334,629,False,@115827 Thanks for your patience. ^KM,NaN,627.0
337,631,False,@115829 I'm sorry your order arrived in this c...,NaN,632.0
339,633,False,@115831 I'm sorry for the wait. Please reach o...,NaN,634.0
341,635,False,@115832 Alexa says both styles are working for...,NaN,636.0
343,637,False,@115834 Were you able to reach us at the link ...,NaN,638.0
345,639,False,"@115834 The Echo Show is supported, please rea...",638,640.0
348,642,False,"@115834 Oh no, I'm sorry for the issues! For t...",641,643.0
350,644,False,@115835 I'm so sorry you didn't receive your p...,645,646.0
352,647,False,@115835 You can also request a call back here ...,NaN,645.0
354,648,False,@115836 Thanks for bringing this to our attent...,NaN,649.0

In [10]:
apple = df[df["author_id"] == "AppleSupport"]

apple[["tweet_id", "inbound", "text",
       "response_tweet_id", "in_response_to_tweet_id"]].head(20)

,tweet_id,inbound,text,response_tweet_id,in_response_to_tweet_id
396,696,False,@115854 We're here for you. Which version of t...,697,698.0
398,699,False,@115854 Lets take a closer look into this issu...,NaN,697.0
401,701,False,@115855 Let's go to DM for the next steps. DM ...,NaN,702.0
403,703,False,@115855 Any steps tried since it started last ...,702,704.0
405,705,False,@115855 That's great it has iOS 11.1 as we can...,"706,704",707.0
407,708,False,@115855 We'd like to look into this with you. ...,707,709.0
411,712,False,"@115856 Hey, let's work together to figure out...",713,714.0
414,716,False,@115857 We'd like to investigate further with ...,NaN,717.0
416,718,False,"@115857 Fill us in on what is happening, then ...",717,719.0
418,720,False,@115859 We've received your DM and will contin...,NaN,721.0
420,722,False,@115859 What's going on? We're hapy to help if...,721,723.0
422,724,False,"@115860 Reach out to us via DM, and we can tak...",NaN,725.0
426,729,False,@115861 You're in the right place; we'll do al...,728,730.0
428,732,False,@115863 Go ahead and send us a DM please. Let ...,NaN,733.0
430,734,False,"@115864 We'd like to help, but we'll need more...",735,736.0
432,737,False,"@115864 To make sure, is iOS 11.1 installed on...",NaN,735.0
434,738,False,@115865 Thanks! Which iOS version is currently...,739,740.0
436,741,False,@115865 Let's check Settings &gt; General &gt;...,742,739.0
438,743,False,@115865 Our pleasure. If you're still having i...,NaN,742.0
440,744,False,@115865 Hi there! What type of device are we w...,740,745.0

In [11]:
uber = df[df["author_id"] == "Uber_Support"]

uber[["tweet_id", "inbound", "text",
      "response_tweet_id", "in_response_to_tweet_id"]].head(20)

,tweet_id,inbound,text,response_tweet_id,in_response_to_tweet_id
463,768,False,@115872 Happy to follow up! Contact us via htt...,"769,770",771.0
465,770,False,@115872 We apologize for the trouble! Send us ...,NaN,768.0
467,772,False,@115874 We're here to help! Send us a note her...,NaN,773.0
469,774,False,"@115875 We’re here to help, Travis! Send us a ...",NaN,775.0
471,776,False,@115876 For more info about UberEats availabil...,NaN,777.0
473,778,False,@115878 We have received your DM and will foll...,779,780.0
476,781,False,@115878 We're sorry to hear this was your expe...,780,782.0
478,783,False,@115880 We're sorry to hear this was your expe...,NaN,784.0
1202,1792,False,@116108 Here to help! Send us a note via https...,1793,1794.0
1204,1795,False,@116108 We're here to help! Send us a DM with ...,NaN,1793.0
1206,1796,False,@116109 We have followed up via DM.,NaN,1797.0
1208,1798,False,@116110 Here to help! Send us a note via https...,1799,1800.0
1211,1801,False,@116111 Here to help! Send us a note via https...,1802,1803.0
1213,1804,False,@116111 We're currently reviewing your email a...,1805,1802.0
1216,1806,False,@116112 We're sorry to hear this was your expe...,NaN,1807.0
1218,1808,False,@116113 Please DM us with your account email a...,NaN,1809.0
1220,1810,False,@116113 Sorry to hear this was your experience...,"1811,1809",1812.0
1268,1864,False,@116127 Here to help! Please DM (direct messag...,1865,1866.0
1408,2096,False,@116168 Happy to further assist you. Can you p...,2097,2098.0
1410,2099,False,"@116168 Hi, Singh. Please send us a DM with yo...",NaN,2097.0

In [12]:
american = df[df["author_id"] == "AmericanAir"]

american[["tweet_id", "inbound", "text",
          "response_tweet_id", "in_response_to_tweet_id"]].head(20)

,tweet_id,inbound,text,response_tweet_id,in_response_to_tweet_id
603,996,False,@115904 We'll be sure to pass along your kind ...,NaN,997.0
605,998,False,@115904 Our apologies for the delay in respond...,997,999.0
608,1001,False,"@115905 Aww, that's definitely a future pilot ...",NaN,1002.0
610,1003,False,@115906 This is a great option for customers w...,1004,1005.0
612,1006,False,@115906 We're sorry for your frustration.,NaN,1004.0
614,1008,False,@115907 It's always a pleasure to have you on ...,NaN,1009.0
616,1061,False,"@115908 Pilots, Potter, Pumpkins and Skeletons...",NaN,1062.0
618,1064,False,@115909 We're glad you got to kick back and en...,NaN,1065.0
1315,1916,False,@116142 We never want your experience to be an...,NaN,1917.0
1317,1918,False,@116143 Thanks for the shout-out and for stopp...,NaN,1919.0
1319,1920,False,@116144 We're sorry for any difficulties that ...,1921,1922.0
1321,1923,False,@116144 They'll be more than happy to walk you...,"1924,1925",1921.0
1324,1926,False,@116144 We're sorry for the long wait. The nex...,1927,1925.0
1326,1928,False,@116144 Fares sell in real time. We're sorry w...,"1929,1930",1927.0
1329,1931,False,@116144 We're glad our Reservations team was a...,1932,1930.0
1332,1934,False,@116145 We're sorry for your frustration. Any ...,NaN,1935.0
1334,1936,False,@116145 An airport agent will be happy to take...,1935,1937.0
1336,1938,False,@116145 Our team will need to assess the damag...,1937,1939.0
1338,1940,False,@116145 We always want to take care of your ba...,1939,1941.0
1340,1944,False,@116146 We're happy when you're happy! That su...,NaN,1945.0

In [18]:
df["tweet_id"] = df["tweet_id"].astype(str)

df["in_response_to_tweet_id"] = (
    df["in_response_to_tweet_id"]
    .astype("Int64")
    .astype("string")
)

In [19]:
brand_tweets = df[df["inbound"] == False][
    ["tweet_id", "author_id", "text"]
].copy()

In [20]:
brand_tweets.head()

  tweet_id   author_id                                               text
0        1  sprintcare  @115712 I understand. I would like to assist y...
3        4  sprintcare  @115712 Please send us a Private Message so th...
5        6  sprintcare  @115712 Can you please send us a private messa...
7       11  sprintcare  @115713 This is saddening to hear. Please shoo...
9       15  sprintcare  @115713 We understand your concerns and we'd l...

In [21]:
brand_tweets = brand_tweets.rename(columns={
    "tweet_id": "brand_tweet_id",
    "author_id": "brand",
    "text": "brand_response"
})

In [22]:
brand_tweets.head()

,brand_tweet_id,brand,brand_response
0,1,sprintcare,@115712 I understand. I would like to assist y...
3,4,sprintcare,@115712 Please send us a Private Message so th...
5,6,sprintcare,@115712 Can you please send us a private messa...
7,11,sprintcare,@115713 This is saddening to hear. Please shoo...
9,15,sprintcare,@115713 We understand your concerns and we'd l...

In [23]:
customer_tweets = df[df["inbound"] == True][
    [
        "tweet_id",
        "author_id",
        "text",
        "in_response_to_tweet_id"
    ]
].copy()

In [24]:
customer_tweets.head()

,tweet_id,author_id,text,in_response_to_tweet_id
1,2,115712,@sprintcare and how do you propose we do that,1
2,3,115712,@sprintcare I have sent several private messag...,4
4,5,115712,@sprintcare I did.,6
6,8,115712,@sprintcare is the worst customer service,<NA>
8,12,115713,@sprintcare You gonna magically change your co...,15

In [25]:
customer_tweets = customer_tweets.rename(columns={
    "tweet_id": "customer_tweet_id",
    "author_id": "customer",
    "text": "customer_message",
    "in_response_to_tweet_id": "brand_tweet_id"
})

In [26]:
customer_tweets.head()

,customer_tweet_id,customer,customer_message,brand_tweet_id
1,2,115712,@sprintcare and how do you propose we do that,1
2,3,115712,@sprintcare I have sent several private messag...,4
4,5,115712,@sprintcare I did.,6
6,8,115712,@sprintcare is the worst customer service,<NA>
8,12,115713,@sprintcare You gonna magically change your co...,15

In [27]:
customer_brand = customer_tweets.merge(
    brand_tweets,
    on="brand_tweet_id",
    how="inner"
)

In [28]:
customer_brand.head(10)

,customer_tweet_id,customer,customer_message,brand_tweet_id,brand,brand_response
0,2,115712,@sprintcare and how do you propose we do that,1,sprintcare,@115712 I understand. I would like to assist y...
1,3,115712,@sprintcare I have sent several private messag...,4,sprintcare,@115712 Please send us a Private Message so th...
2,5,115712,@sprintcare I did.,6,sprintcare,@115712 Can you please send us a private messa...
3,12,115713,@sprintcare You gonna magically change your co...,15,sprintcare,@115713 We understand your concerns and we'd l...
4,16,115713,@sprintcare Since I signed up with you....Sinc...,17,sprintcare,@115713 H there! We'd definitely like to work ...
5,22,115716,@Ask_Spectrum Would you like me to email you a...,21,Ask_Spectrum,@115716 What information is incorrect? ^JK
6,26,115716,@Ask_Spectrum I received this from your corpor...,25,Ask_Spectrum,@115716 Our department is part of the corporat...
7,23,115716,@Ask_Spectrum The correct way to do it is via ...,21,Ask_Spectrum,@115716 What information is incorrect? ^JK
8,24,115716,@Ask_Spectrum That is INCORRECT information I ...,28,Ask_Spectrum,@115716 The information pertaining to the acco...
9,35,115719,@VerizonSupport I finally got someone that hel...,34,VerizonSupport,@115719 Help has arrived! We are sorry to see ...

In [29]:
customer_brand.shape

(559849, 6)

In [30]:
customer_brand["brand"].nunique()

108

In [31]:
customer_brand["brand"].value_counts().head(20)

brand
AmazonHelp         100503
AppleSupport        36658
Uber_Support        22160
VirginTrains        18450
AmericanAir         18045
SpotifyCares        15096
Delta               14470
GWRHelp             13127
ATVIAssist          13055
VerizonSupport      12953
Tesco               12812
British_Airways     12485
XboxSupport         11833
TMobileHelp         11662
SouthwestAir        11192
AskPlayStation       9751
Ask_Spectrum         9536
sainsburys           9331
hulu_support         9142
comcastcares         8906
Name: count, dtype: int64

In [32]:
candidate_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Uber_Support",
    "AmericanAir"
]

customer_brand[
    customer_brand["brand"].isin(candidate_brands)
]["brand"].value_counts()

brand
AmazonHelp      100503
AppleSupport     36658
Uber_Support     22160
AmericanAir      18045
Name: count, dtype: int64

In [33]:
for brand in candidate_brands:
    print("\n" + "=" * 80)
    print(brand)
    print("=" * 80)

    messages = customer_brand[
        customer_brand["brand"] == brand
    ]["customer_message"]

    for message in messages.head(20):
        print("-", message)

================================================================================
AmazonHelp
================================================================================
- @AmazonHelp ありがとうございます。
今、電話で主人が対応していただいてます。
- @AmazonHelp 電話で対応してもらいましたが改良されませんでした。
保証期間も過ぎてるので買い直しになるんでしょうね。
- @AmazonHelp こちらこそありがとうございました。
- @AmazonHelp 3 different people have given 3 different answers and I still don't have my order. Says delivered Saturday, was not, I was home all day
- @AmazonHelp I frankly don't have the patience for another chat with your "customer service" people today.
- @AmazonHelp Okay, danke für die Info
- @AmazonHelp @115826 Yeah this is crazy we’re less than a week away and still no Shipping Information on something that we Pre-ordered back in August
- @AmazonHelp Hi ready for some help
- @AmazonHelp Nothing there helped me with the Echo Show
- @AmazonHelp That page is useless - doesn’t allow me to state it hasn’t been delivered; only tells me it has! How can you sort this out?
- @AmazonHelp I don't want a form to fill out that logs a response no one reads. I want to prevent AMZL from touching my stuff. Possible, or no?
- @AmazonHelp Already started the return. UPS gets it from my doorstep tomorrow. Order 111-5014070-4118645
- @AmazonHelp Already handled, just venting. It was a pretty big bummer.
- @AmazonHelp Aww your reply made her night!
- @AmazonHelp I just said it's been sorted! I've been refunded! I'm just not impressed with the service any more.
- @AmazonHelp Details sent. Please check.
- @AmazonHelp Already contacted 3-4 times in the last month. But all I got was assurance that matter is escalated &amp; new status will be provided in 1 day!
- @AmazonHelp but I can’t find the options to cancel or re-order?
- @AmazonHelp Thanks for quick response. Pic attached. https://t.co/yNhYE638YS
- @AmazonHelp Thats the thing I told customer service. I created a new email address for the Prime trial and forgot it. What can I do so I'm not charged?

================================================================================
AppleSupport
================================================================================
- @AppleSupport The newest update. I️ made sure to download it yesterday.
- @AppleSupport Tried resetting my settings .. restarting my phone .. all that
- @AppleSupport This is what it looks like https://t.co/XCQU2l4xUB
- @AppleSupport I️ have an iPhone 7 Plus and yes I️ do
- @AppleSupport Just sent you all my DM
- @AppleSupport This is what is happening... https://t.co/X3SZSJXfAT
- @AppleSupport are the call centres closed for the night?
- @AppleSupport @115861 We’re going to need you to share the answers Angela. I️ can’t stand this!
- @AppleSupport I have the iPhone 6s Plus and just did the most recent update.
- @AppleSupport iOS 11.0.3
- @AppleSupport Okey. Thank you! 🤗
- @AppleSupport iPhone 7 Plus 😊
- @AppleSupport I need the software update urgently. The battery lasts literally half a day 🙍🏼🙁@AppleSupport
- @AppleSupport Yes it did, 11.0.3
- @AppleSupport I can not find an option to get it there. It was just always there when playing.
- @AppleSupport The app is still there. But no longer able to control it from the lockscreen.
- @AppleSupport I️ just updated it and it’s still coming up https://t.co/22RZsQyTbh
- @AppleSupport Thanks, thing is I still have like 81 cents in credit and won't let me do that until I have zero credit
- @AppleSupport Awesome, thanks
- @AppleSupport it has, but not for some time now. i’ve tried with two different apple ids but it’s still not showing up on my phone

================================================================================
Uber_Support
================================================================================
- @Uber_Support Already did that was told we requested to dropped off somewhere different which is completely false.
- @Uber_Support @115879 wouldn't do this to me 😔
- @Uber_Support Why is there no phone number ?? I'm literally stranded and now I have to wait for an automated reply this is ridiculous
- @Uber_Support I did. No response.
- @Uber_Support Thanks! I appreciate it. Not sure what happened.
- @Uber_Support I already dm y'all about 30 mins ago, check it out it is long and detailed.
- @Uber_Support  https://t.co/Fc42zHkmDA
- @Uber_Support i do not see we're the trid if is listed on the app.. i sent in a few message
- @Uber_Support pls check dm
- @Uber_Support done please check
- @Uber_Support Sent a DM... Hope you could help soon.
- @Uber_Support Welp... I guess that's one bibimbap order I'm never gonna receive. Good thing I used a first time order promotion. Not a good first impression though.
- @Uber_Support Haha nah I’m good it got here eventually lol
- @Uber_Support I submitted an online request and expect a cancellation credit to my account as I would of had to pay. Thank you!
- @Uber_Support Thank you for your response. Put in a request and am waiting for reply!
- @Uber_Support The thing is, it’s the exact same reliability and speed as @154... so why would I pay $15 more for the same product or wait for later when I can just give them my money? Which is what I did.
- @Uber_Support Is there a way I can address a specific issue? Though i already received compensation for that ride i reported, I'd like to mention it would've been avoided if the route to my location was plotted correctly. The map told him to pass through a route that had a dead end
- @Uber_Support i’m already registered as a driver, lower the age requirement or let me bypass the rule please
- @Uber_Support i’m 4 months away from being 21 and have driving experience including delivery. i feel i should be able to drive now instead of waiting to be 21
- @Uber_Support That's a big lie otherwise my account would be up and running, stop lying, I'll make it public all the lies your guys have told me, been told it would only take 48 hours been waiting 5 DAYS

================================================================================
AmericanAir
================================================================================
- @AmericanAir Erica on the lax team is amazing give her a raise ty
- @AmericanAir Right, but I earned those. I also shouldn’t have to pay to pass them to my own spouse. You need to change your program.
- @AmericanAir already did...changed browsers, did all my techie tricks and still can't make a reservation after 1 hour!!
- @AmericanAir been on phone and hold for past 45 mins. looking bleak
- @AmericanAir ........still....on....hold.....they made the booking. I am trying to pay.....so #frustrating.
- @AmericanAir well now i am told the ticket cost is an additional $200/person to pay....because of the wait....omg
- @AmericanAir i don't think it changes within minutes. This is a scam
- @AmericanAir finally booked and they honored lower fare....that was still available on line
- @AmericanAir Me too, but it shouldn't be this hard. Nearly 2 hours.
- @AmericanAir Well how much does that help me now?
- @AmericanAir I was long gone from the airport by then
- @AmericanAir No I was not able to
- @AmericanAir Oh god, we’re in ascent and this baby just went full Chucky. Happy Halloween?
- @AmericanAir Like, any?
- @AmericanAir I gotta admit, this baby has some commitment. #stillgoing
- @AmericanAir Bought a flight pass to tell you guys this baby is still Chucky possessed screaming. Only seats available in cabin are the ones around me.
- @AmericanAir I'm aware. Fits in overhead.This was a return trip. Had same luggage going. This was pre-security. Gate chck, ok, but Empty overheads on flt
- @AmericanAir Yes I did! I'm sending you a DM now.
- @AmericanAir I’d still rather have a screen though. Rather not cause neck problems looking down all flight at a tablet
- @AmericanAir Now 10:50 😩.

In [34]:
candidate_brands = [
    "AmazonHelp",
    "AppleSupport",
    "Uber_Support",
    "AmericanAir"
]

interaction_counts = (
    customer_brand[
        customer_brand["brand"].isin(candidate_brands)
    ]
    .groupby("brand")
    .size()
    .sort_values(ascending=False)
)

interaction_counts

brand
AmazonHelp      100503
AppleSupport     36658
Uber_Support     22160
AmericanAir      18045
dtype: int64

In [35]:
customer_counts = (
    customer_brand[
        customer_brand["brand"].isin(candidate_brands)
    ]
    .groupby("brand")["customer"]
    .nunique()
    .sort_values(ascending=False)
)

customer_counts

brand
AmazonHelp      40671
AppleSupport    23668
Uber_Support    12780
AmericanAir      9699
Name: customer, dtype: int64

In [36]:
customer_brand["customer_length"] = (
    customer_brand["customer_message"]
    .str.split()
    .str.len()
)

customer_brand["response_length"] = (
    customer_brand["brand_response"]
    .str.split()
    .str.len()
)

In [37]:
customer_brand[
    customer_brand["brand"].isin(candidate_brands)
].groupby("brand")[[
    "customer_length",
    "response_length"
]].agg(["mean", "median"])

             customer_length        response_length
                        mean median            mean median
brand
AmazonHelp         18.315165   17.0       20.729650   20.0
AmericanAir        18.666112   18.0       19.187088   20.0
AppleSupport       15.773583   14.0       22.986688   21.0
Uber_Support       16.761913   15.0       20.010334   19.0

In [38]:
for brand in candidate_brands:
    print("\n" + "=" * 80)
    print(brand)
    print("=" * 80)

    sample = (
        customer_brand[
            customer_brand["brand"] == brand
        ]
        .sample(
            n=min(20, len(customer_brand[customer_brand["brand"] == brand])),
            random_state=42
        )
    )

    for _, row in sample.iterrows():
        print("\nCUSTOMER:")
        print(row["customer_message"])

        print("BRAND:")
        print(row["brand_response"])

================================================================================
AmazonHelp
================================================================================

CUSTOMER:
@AmazonHelp Something was supposed to be delivered today but it says on the order page ‘arrival at incorrect carrier facility’ and to ‘check back tuesday’ (yesterday)
BRAND:
@706559 Hi James, thanks for getting in touch. Without posting any of your account details, can you tell us how we can help you? ^BZ

CUSTOMER:
@AmazonHelp Thank you 🙌🏻
BRAND:
@516907 I'm sorry for the unexpected charge! You're able to cancel the membership w/ us here: https://t.co/5tjh8NQLaW ^KP

CUSTOMER:
@AmazonHelp C’est Amazon Logistics
BRAND:
@816249 Bonsoir, je suis navrée pour la gêne occasionné, quel est le transporteur en charge de la livraison, S'il vous plaît ? ^ASZ

CUSTOMER:
@AmazonHelp yes I have been through all of the steps. I will check with nighbours further down the street tomorrow, but no notification of delivery 1/2
BRAND:
@128483 We're here to help! Have you explored all steps to locate your parcel here: https://t.co/8i2HpyhtwC ? Let us know, please! ^JE

CUSTOMER:
@AmazonHelp But kindly help me to get it faster and help me to get it on 16 . I a k so know promise date but can't you do something
BRAND:
@680435 estimated delivery date given for the package to be delivered. Please don't provide your details, we consider it personal information. Our Twitter page is visible to public. 2/2 ^MK

CUSTOMER:
@AmazonHelp Well you couldn't resolve the 'issue'" your colleagues messed me around and even your superiors did. I genuinely feel  worthless to you. :(
BRAND:
@152461 Sorry to hear that! Has the issue been resolved? ^AT

CUSTOMER:
@AmazonHelp Jk I figured it out ty tho
BRAND:
@251433 I am very sorry about the troubles with the Prime Membership, Claire! Let's see how we can help!  Can you tell me which Amazon site you order from? ^FR

CUSTOMER:
@AmazonHelp Voilà j'ai envoyé en message privé
BRAND:
@683416 Pourriez-vous me fournir le lien qui mène vers la page détaillée de l'article?
^MD

CUSTOMER:
@AmazonHelp Sick of ur response.No need of it.
BRAND:
@122868 Please reach out to us from the link provided earlier and we'll check this. (2/2)^YP

CUSTOMER:
@AmazonHelp MAY I KNOW HOW MANY TIMES I NEED TO UPDATE..I AM NOY GOING TO UPDATE ANY MORE..IF U WANT TO CONTINUE ..U CAN ELSE CLOSE THIS DISCUSSION.
BRAND:
@283696 We haven't received your details. Kindly share your details via link provided earlier and we'll get in touch with an update soon. Appreciate your understanding. ^AK

CUSTOMER:
@AmazonHelp Made order next Saturday failed to be delivered on Wednesday and Thursday rang yesterday and this afternoon around 12:30 was promised that would be delivered today then rang again this afternoon told be delivered until Monday now been waiting 7 days one of worse customer services
BRAND:
@232821 Hi Raj, without going into any personal account info could you please tell us more about this? ^HS

CUSTOMER:
@AmazonHelp none at all 😁
BRAND:
@791488 We do not have any account access here on Twitter. What information was phone support able to provide? ^TR

CUSTOMER:
@AmazonHelp No resolution provided. Still facing issue
BRAND:
@182608 Sorry to know that you're unable to access your account. As per the screenshot posted earlier, the resolution provided (1/2)^SQ

CUSTOMER:
@AmazonHelp Sure. I loved the positive reply! :)
BRAND:
@131820 Thanks a bunch for sharing your details. We shall reach out to you at the earliest to make things right. ^CB

CUSTOMER:
@AmazonHelp Yes thanks. I’ve picked it up.
BRAND:
@216160 Glad to hear that it's now made its way to you! Are you able to collect it from the Amazon Locker? ^TI

CUSTOMER:
@AmazonHelp Yes reordered no delivery date and customer services advised they'd speak to the relevant department however 9 days later still no shipment.
BRAND:
@146755 Thanks for confirming! Did you take the advise and reorder the ite? If so, were you given a new delivery date? ^HC

CUSTOMER:
@AmazonHelp Thanks
BRAND:
@493914 Please follow the steps provided here: https://t.co/RNYfWuV8rB. Do let us know for any further concern. ^AM

CUSTOMER:
@AmazonHelp What is the status still no response
BRAND:
@159037 Thank you for the heads up. Our team will reach out to you at the earliest. Appreciate your understanding. ^HD

CUSTOMER:
@AmazonHelp I want it today else cancel it
BRAND:
@413685 That is a bad miss from our side, write to us here: https://t.co/GIJyeYqKE0 &amp; we'll fix this for you. ^MJ

CUSTOMER:
@AmazonHelp I filled the form yesterday and still waiting for YOU to revert. 3rd day of #amazonprime delivery.#Joke
BRAND:
@193740 I understand your concern. Please share your details here: https://t.co/GIJyeYqKE0 and I'll get in touch with you. ^HD

================================================================================
AppleSupport
================================================================================

CUSTOMER:
@AppleSupport Nope 🤔
BRAND:
@623037 Do you have any messages inside the Messages app that look like they are to someone you don't have a contact for?

CUSTOMER:
@AppleSupport They are not on the same iOS one is 11.0.2 and the other is 11.1.2 I am updating the iPhone 8plus now and Ithink this should fix the problem so both are on the same software version
BRAND:
@276131 We'll gladly lend a hand, so you can restore all of your important data back to your new iPhone. First, can you tell us which iOS version is currently installed on this iPhone? Also, what was the iOS version installed on the device that this backup is from?

CUSTOMER:
@AppleSupport thank you
BRAND:
@514881 We'd be happy to help. Send us a DM with a few more details and we can start there. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport I️ thought that was a good idea but I️ can see that it isn’t working https://t.co/NBPFOxXHcE
BRAND:
@628699 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9

CUSTOMER:
@AppleSupport After it says verifying it restarts automatically
BRAND:
@123188 We can help! What happens after it says verifying. Is that when it restarts or are you restarting it manually?

CUSTOMER:
@AppleSupport Is this what you want? https://t.co/4f0AP0c3uz
BRAND:
@265100 Thank you. Please send us a DM with a screenshot of Apple Watch &gt; My Watch &gt; Health. We'd like to look into this for you. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport Confirmed. Doesn't Respect volume setting  at all
BRAND:
@381981 Got it. If you're still having trouble, feel free to send us a DM and we'll investigate this further with you. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport Thank you will do
BRAND:
@769290 We appreciate you reaching out with suggestions. Please use our feedback website to get your suggestions to the right place: https://t.co/eTPVYVFyd8

CUSTOMER:
@AppleSupport Yes "there was an error downloading the software"
BRAND:
@666880 We'd like to help! Are you getting any error messages?

CUSTOMER:
@AppleSupport @AppleSupport thanks for the info! Would have been maybe helpful to have a video on the phone to explain these things with the new IOS.
BRAND:
@188704 Control Center has changed the functionality for Wi-Fi and Bluetooth. There's an explanation here: https://t.co/G7BHuQnDS6

CUSTOMER:
@AppleSupport Sizin allah belanızı versin
BRAND:
@669812 We offer support via Twitter in English. Contact us for help in your preferred language here: https://t.co/IBIY3w3RGR

CUSTOMER:
@AppleSupport Phone shuts off when it wants no matter the battery life. And made my phone sluggish. I’m confused, aren’t updates out there to improve
BRAND:
@327474 Let us help out. Tell us more details about what you're experiencing. Also, which version of iOS 11 are you running?

CUSTOMER:
@AppleSupport @782410 Should I upgrade my IPhone 6 Plus to OIS 11? Thank you.
BRAND:
@782410 Is iOS 11.1.2 the version currently installed on it, and have you tried any steps so far besides restarting it? What's the issue with the Messages app?

CUSTOMER:
@AppleSupport What about seeing that in messages on my MacBook Air?
BRAND:
Seeing an i️ whenever you type “i" in iOS 11.1?

Fix it by installing the latest software update.
https://t.co/NX7ObPTLvY

CUSTOMER:
@AppleSupport Thank you
BRAND:
@488024 We'd like to know more about what you're experiencing. Let us know and we'll see how we can help.

CUSTOMER:
@AppleSupport It’s iOS 11.2
BRAND:
@260690 Thank you for following up with us. Which iOS version is your device running?

CUSTOMER:
@AppleSupport 11.1 Public beta 5
BRAND:
@444937 We're excited to look into this with you. Could you let us know which version of iOS you have installed?

CUSTOMER:
@AppleSupport 1: ios 11.0.3
2: everything in the comments here:https://t.co/94oZBnIEnm
3: the worse ios deployment to date period!
4: lost product faith
BRAND:
@438651 We're here to help with any issues you have. What is going on?

CUSTOMER:
@AppleSupport Thanks. Now how do you explain my phone shutting itself off randomly and being non-responsive to any amount or duration of key presses?
BRAND:
@489557 We're here to help. Check out our article here: https://t.co/xU1AGHStV6 DM us any other questions. https://t.co/GDrqU22YpT

CUSTOMER:
@AppleSupport Yeah kindly check my reply
BRAND:
@173776 Hi. We're here to help you. DM us and we can take a closer look. https://t.co/GDrqU22YpT

================================================================================
Uber_Support
================================================================================

CUSTOMER:
@Uber_Support Lovely, thank you.
BRAND:
@736208 Here to help! Send us a note at https://t.co/1xM0TILvAI so our team can connect right away.

CUSTOMER:
@Uber_Support Issue has not been resolved. Very inconvenient for business profile users.
BRAND:
@305373 We've followed up via DM so please check your inbox.

CUSTOMER:
@Uber_Support It was on November 2nd. I am still unable to use the service 😤
BRAND:
@490711 It seems a member of our team has reached out to you. Please check your email and follow up with them there.

CUSTOMER:
@Uber_Support Pls get drivers NOT to pick up jobs when they are still on another job,you made me late for trains 3rd time in a row!
BRAND:
@384490 Here to help! Send us a note at https://t.co/WFtPA6RjWt so our team can connect right away.

CUSTOMER:
@Uber_Support When
BRAND:
@375710 We're here to help! Please let us know some info about the issue you're having. Our team will follow up.

CUSTOMER:
@Uber_Support  my drived faked that m already in trip bit m still waiting. Kindly look into this urgently. Send another ride asap
BRAND:
@184913 We're ready to look into this. Please send us a message with details of the trip here: https://t.co/biBCTHpjMe so we can follow up.

CUSTOMER:
@Uber_Support  https://t.co/FOAMyDATWp
BRAND:
@528154 We've followed up within your Direct Messages, Lovina!

CUSTOMER:
@Uber_Support stupid fellow, i know ur mailing Escalation.... Response properly
BRAND:
@262818 Here to help! Send us a note here https://t.co/e8HVorX5rh so we can assist.

CUSTOMER:
@Uber_Support Sure thanks for the response.
Submitted a help request as mentioned in mail
BRAND:
@751319 In an effort to enhance your support experience, and to avoid further confusion we'll be following up any further questions or concerns you may have through in-app support. Thank you so much for your patience and understanding with us.

CUSTOMER:
@Uber_Support The inquiry doesn’t actually fit that bill. Spelling in that text was wrong. No account abuse detected. Just this message?
BRAND:
@429807 We're here to help! Please send us a note via https://t.co/J1AzB6DDDr so we can connect.

CUSTOMER:
@Uber_Support Will do
BRAND:
@560287 We're sorry to hear about this. Please have the account holder sign in and visit us at https://t.co/7RWapHc4XN so our team can assist.

CUSTOMER:
@Uber_Support  https://t.co/kvBdJAgy1L
BRAND:
@181728 Oh no! Please DM us the email linked to your account so we can look into this for you. We look forward to your response.

CUSTOMER:
@Uber_Support Currently shows driver income includes sales tax and black car fund? Then the year-end drivers need to pay their own sales tax and black car fund it?
BRAND:
Update: We're still experiencing a delay with earnings showing up in the Uber Driver app. The amount of your earnings will not be impacted. We're working hard to get this resolved and apologize for any inconvenience.

CUSTOMER:
@Uber_Support Cleaning fee was refunded and honestly, I wish I could be refunded for the entire ride too, due to the fraudulent claim.  Unprofessional
BRAND:
@477486 We'll be happy to take a closer look. Send us a note via https://t.co/a6RfeBkKmr so our team can connect.

CUSTOMER:
@Uber_Support I ordered this drive from a different number which was 923234256690 driver’s name is Mehfooz - Wagon R Sunday 3:58 pm he didn’t turn the AC
BRAND:
@120787 We're here to help! Please send us a note via https://t.co/aBEgvdNWQN so we can connect.

CUSTOMER:
@Uber_Support Thanks for wasting it more
BRAND:
@284042 We can look into this with you, Archit. Can you please send a note our way via https://t.co/L2aXwAc0Tb?

CUSTOMER:
@Uber_Support Oh, I don't have a complaint @115877 as I don't use your service. Everybody knows fast food is best enjoyed immediately after purchase...in the car
BRAND:
@803617 We're sorry to hear this. Please send us a note here; https://t.co/OWBkgXcbMl so we can help.

CUSTOMER:
@Uber_Support @126796 Im having the same problem its not showing up in app!
BRAND:
@126796 Happy to help. You can go here https://t.co/3h8wdQ4EJK, to find out more info.

CUSTOMER:
@Uber_Support __email__
BRAND:
@451658 Happy to help! Please confirm your email address or phone number so we can further assist.

CUSTOMER:
@Uber_Support I submitted one and have received no reply yet. 😐
BRAND:
@379063 Thank you for reaching out! In order to further assist you, we'll need you to send us a note at https://t.co/iATniAbeos.

================================================================================
AmericanAir
================================================================================

CUSTOMER:
@AmericanAir Not cutting it. You should learn from @115879 ‘s automated responses
BRAND:
@504066 We're sorry for the delay. We'll have you in the air as soon as we can and we appreciate your patience.

CUSTOMER:
@AmericanAir Nah, I'll just post them live thanks #SharingIsCaring
BRAND:
@330121 We're happy to help in anyway we can. Please follow and share the details in DMs.

CUSTOMER:
@AmericanAir Your airport team has been no help. Told me to call customer service instead of rescheduling my flight. Everyone keeps passing the buck.
BRAND:
@474024 We're very sorry we weren't able to confirm you on your preferred flight right away. Please continue working with our airport team.

CUSTOMER:
@AmericanAir Now she has to miss a major 5 figure deal she is needed to be a part of. They weren’t accommodating at all and closed the gate before the 10 Min window.
BRAND:
@637533 What's wrong, Camille. We'd like to help if we can.

CUSTOMER:
@AmericanAir What number can I call
BRAND:
@342125 We're unable to refund a ticket for a trip you're taking. Please let us know if we can help in someway.

CUSTOMER:
@AmericanAir But how can one penalize someone for not filling a seat that they have already paid for?  If anything, they should be reimbursed if their seat is filled by someone else, yes?
BRAND:
@641060 It depends on the type of ticket you hold. Please call our folks in Reservations at 800-433-7300 and they'll take a peek at your fare.

CUSTOMER:
@AmericanAir 👍🏽
BRAND:
@186869 Our gate team will make sure everyone is taken great care of. Please let their team know if you have questions.

CUSTOMER:
@AmericanAir Why a change fee when this was caused by a natural disaster? Since a fire prevented me from going to Santa Rosa, I have to pay $200/ticket? https://t.co/yqNpgrFLY9
BRAND:
@542725 We're working with our customers to assist them as best as possible. Please DM your record locator so we can look into this further.

CUSTOMER:
@AmericanAir Saying sorry is not a solution. Quite disappointed in my first experience with American, could be my last.
BRAND:
@783762 We're sorry you're not enjoying yourself, Alex. We always want you to have a great experience with us.

CUSTOMER:
@AmericanAir For 2 years I have been traveling w @AmericanAir and never get upgraded, I am tired of this. With @delta I was always upgraded.
BRAND:
@279772 We always want you up front with us, Selma, and we're so sorry we were unable to upgrade you today.

CUSTOMER:
@AmericanAir @127032 I’m curious to know what they DMd you???
BRAND:
@127032 Please check your DMs for a message.

CUSTOMER:
@AmericanAir And I understand safety but flight staff acting like it is an inconvenience to answer questions is my main issue.
BRAND:
@444007 Safety is our top priority and we apologize for the delay. Our team's preparing as quickly as they can for takeoff.

CUSTOMER:
@AmericanAir Por todas las redes sociales seguire dia tras dia señalando a @AmericanAir como una compañia poco seria y sinvergüenza
BRAND:
@810097 Please continue to work with our baggage folks. Well have you reunited with your bag as soon as possible.

CUSTOMER:
@AmericanAir And if you don't, then what am I supposed to do? I'm flying out of DFW, which is where WaPo says most of the flights without pilots are. Would appreciate a chance to cancel without penalty rather than hold my breath you'll get it fixed in time.
BRAND:
@134908 We know how important the holidays are and fully expect to avoid cancellations during this time, Kristen.

CUSTOMER:
@AmericanAir Should’ve booked on AA. Rushing to NYC for an urgent meeting and will now miss it thanks to the @JetBlue delay.
BRAND:
@318258 Yes, Piyush. AA18 is currently on time.

CUSTOMER:
@AmericanAir Now a flight from Charlotte 2 SFO that I can’t use my computer because there is no power &amp; can’t watch or listen to anything either.  Bleh!
BRAND:
@360958 We have a responsibility to handle every situation with professionalism and we're sorry that you experienced differently today.

CUSTOMER:
@AmericanAir Least of my worries now. Waiting over an hour for my bag was just unacceptable @AmericanAir
BRAND:
@253049 What a bummer. You can check the ending on your next flight if you can wait that long!

CUSTOMER:
@AmericanAir Sent. Thanks.
BRAND:
@623378 We'd be happy to help, David. Can you verify in DMs which record locator this in reference to?

CUSTOMER:
@AmericanAir Ahhhhh. Noted. Time for me to diet
BRAND:
@666652 We do post seat sizes, Stan. Click here to view them on our website. https://t.co/Cqtk8kHZip

CUSTOMER:
@AmericanAir @188393 Unless they don't, in which case, they won't care.
BRAND:
@188393 It's our pleasure to have you fly with us today. Time to sit back, relax and our crew will take great care of you!

In [39]:
american_sample = (
    customer_brand[
        customer_brand["brand"] == "AmericanAir"
    ]
    .sample(30, random_state=42)
)

for _, row in american_sample.iterrows():
    print("\n" + "=" * 80)
    print("CUSTOMER:")
    print(row["customer_message"])
    print("\nAMERICAN AIR RESPONSE:")
    print(row["brand_response"])

================================================================================
CUSTOMER:
@AmericanAir Not cutting it. You should learn from @115879 ‘s automated responses

AMERICAN AIR RESPONSE:
@504066 We're sorry for the delay. We'll have you in the air as soon as we can and we appreciate your patience.

================================================================================
CUSTOMER:
@AmericanAir Nah, I'll just post them live thanks #SharingIsCaring

AMERICAN AIR RESPONSE:
@330121 We're happy to help in anyway we can. Please follow and share the details in DMs.

================================================================================
CUSTOMER:
@AmericanAir Your airport team has been no help. Told me to call customer service instead of rescheduling my flight. Everyone keeps passing the buck.

AMERICAN AIR RESPONSE:
@474024 We're very sorry we weren't able to confirm you on your preferred flight right away. Please continue working with our airport team.

================================================================================
CUSTOMER:
@AmericanAir Now she has to miss a major 5 figure deal she is needed to be a part of. They weren’t accommodating at all and closed the gate before the 10 Min window.

AMERICAN AIR RESPONSE:
@637533 What's wrong, Camille. We'd like to help if we can.

================================================================================
CUSTOMER:
@AmericanAir What number can I call

AMERICAN AIR RESPONSE:
@342125 We're unable to refund a ticket for a trip you're taking. Please let us know if we can help in someway.

================================================================================
CUSTOMER:
@AmericanAir But how can one penalize someone for not filling a seat that they have already paid for?  If anything, they should be reimbursed if their seat is filled by someone else, yes?

AMERICAN AIR RESPONSE:
@641060 It depends on the type of ticket you hold. Please call our folks in Reservations at 800-433-7300 and they'll take a peek at your fare.

================================================================================
CUSTOMER:
@AmericanAir 👍🏽

AMERICAN AIR RESPONSE:
@186869 Our gate team will make sure everyone is taken great care of. Please let their team know if you have questions.

================================================================================
CUSTOMER:
@AmericanAir Why a change fee when this was caused by a natural disaster? Since a fire prevented me from going to Santa Rosa, I have to pay $200/ticket? https://t.co/yqNpgrFLY9

AMERICAN AIR RESPONSE:
@542725 We're working with our customers to assist them as best as possible. Please DM your record locator so we can look into this further.

================================================================================
CUSTOMER:
@AmericanAir Saying sorry is not a solution. Quite disappointed in my first experience with American, could be my last.

AMERICAN AIR RESPONSE:
@783762 We're sorry you're not enjoying yourself, Alex. We always want you to have a great experience with us.

================================================================================
CUSTOMER:
@AmericanAir For 2 years I have been traveling w @AmericanAir and never get upgraded, I am tired of this. With @delta I was always upgraded.

AMERICAN AIR RESPONSE:
@279772 We always want you up front with us, Selma, and we're so sorry we were unable to upgrade you today.

================================================================================
CUSTOMER:
@AmericanAir @127032 I’m curious to know what they DMd you???

AMERICAN AIR RESPONSE:
@127032 Please check your DMs for a message.

================================================================================
CUSTOMER:
@AmericanAir And I understand safety but flight staff acting like it is an inconvenience to answer questions is my main issue.

AMERICAN AIR RESPONSE:
@444007 Safety is our top priority and we apologize for the delay. Our team's preparing as quickly as they can for takeoff.

================================================================================
CUSTOMER:
@AmericanAir Por todas las redes sociales seguire dia tras dia señalando a @AmericanAir como una compañia poco seria y sinvergüenza

AMERICAN AIR RESPONSE:
@810097 Please continue to work with our baggage folks. Well have you reunited with your bag as soon as possible.

================================================================================
CUSTOMER:
@AmericanAir And if you don't, then what am I supposed to do? I'm flying out of DFW, which is where WaPo says most of the flights without pilots are. Would appreciate a chance to cancel without penalty rather than hold my breath you'll get it fixed in time.

AMERICAN AIR RESPONSE:
@134908 We know how important the holidays are and fully expect to avoid cancellations during this time, Kristen.

================================================================================
CUSTOMER:
@AmericanAir Should’ve booked on AA. Rushing to NYC for an urgent meeting and will now miss it thanks to the @JetBlue delay.

AMERICAN AIR RESPONSE:
@318258 Yes, Piyush. AA18 is currently on time.

================================================================================
CUSTOMER:
@AmericanAir Now a flight from Charlotte 2 SFO that I can’t use my computer because there is no power &amp; can’t watch or listen to anything either.  Bleh!

AMERICAN AIR RESPONSE:
@360958 We have a responsibility to handle every situation with professionalism and we're sorry that you experienced differently today.

================================================================================
CUSTOMER:
@AmericanAir Least of my worries now. Waiting over an hour for my bag was just unacceptable @AmericanAir

AMERICAN AIR RESPONSE:
@253049 What a bummer. You can check the ending on your next flight if you can wait that long!

================================================================================
CUSTOMER:
@AmericanAir Sent. Thanks.

AMERICAN AIR RESPONSE:
@623378 We'd be happy to help, David. Can you verify in DMs which record locator this in reference to?

================================================================================
CUSTOMER:
@AmericanAir Ahhhhh. Noted. Time for me to diet

AMERICAN AIR RESPONSE:
@666652 We do post seat sizes, Stan. Click here to view them on our website. https://t.co/Cqtk8kHZip

================================================================================
CUSTOMER:
@AmericanAir @188393 Unless they don't, in which case, they won't care.

AMERICAN AIR RESPONSE:
@188393 It's our pleasure to have you fly with us today. Time to sit back, relax and our crew will take great care of you!

================================================================================
CUSTOMER:
@AmericanAir I’m actually flying you guys in a couple weeks see look. I’m very excited https://t.co/ZIxJIRHM6E

AMERICAN AIR RESPONSE:
@739310 No worries! We'll see you and your friend next time.

================================================================================
CUSTOMER:
@AmericanAir Main issue is people who PAID for Priority &amp; ME trying to do YOUR job by keeping Group 9 from boarding but Gate Agent letting them in

AMERICAN AIR RESPONSE:
@397103 We're so sorry to hear that happened, Hugo. Did you ask our gate agent to add you on the list? Give us a moment and meet us in DM.

================================================================================
CUSTOMER:
@AmericanAir Just did. Thank you!

AMERICAN AIR RESPONSE:
@311058 Kaitlyn, we always want our customer to be updated with the latest details. Please follow and DM your record locator.

================================================================================
CUSTOMER:
@AmericanAir We’re all bronze members friends get priority boarding I don’t very strange. Great Start!!!😡😡😡

AMERICAN AIR RESPONSE:
@122134 You'll get plenty of rest flying over the Atlantic, Jonathan. The fun will begin one you arrive in LAS!

================================================================================
CUSTOMER:
@AmericanAir Appreciate apologies but was told my bag NEVER left Ohare Mon, now they say it's not here. Not fair for Vets to be treated like this!! HELP

AMERICAN AIR RESPONSE:
@382732 We don't currently have an update. Our apologies.

================================================================================
CUSTOMER:
@AmericanAir don’t fly @137434 and will now no longer fly with American. Should tell higher ups to reconsider the mode

AMERICAN AIR RESPONSE:
@599893 We hope to see you on board. We offer a variety of fares that offers our customers different services.

================================================================================
CUSTOMER:
@AmericanAir While I couldn't seem to board an on-time plane today, apparently I'm still better off than my suitcase. #baggageMIA

AMERICAN AIR RESPONSE:
@214345 Thank you, Ashley. Your support means a lot to us and our #AATeam.

================================================================================
CUSTOMER:
@AmericanAir Seriously - the delays and customer service have gotten worse since the US Airways acquisition. You just got a new loyal customer, @Delta.

AMERICAN AIR RESPONSE:
@174443 We're sorry for the lateness today. We appreciate you hanging in there.

================================================================================
CUSTOMER:
@AmericanAir The gate lady hooked it up, you’re back on my good side

AMERICAN AIR RESPONSE:
@783665 Meet us in DM with your record locator and we'll take a peek.

================================================================================
CUSTOMER:
@AmericanAir Okay thanks I responded

AMERICAN AIR RESPONSE:
@180823 We see your DMs and we'll be responding shortly.

In [41]:
american_messages = customer_brand[
    customer_brand["brand"] == "AmericanAir"
][[
    "customer_tweet_id",
    "customer_message",
    "brand_response"
]].copy()

In [42]:
american_messages.shape

(18045, 3)

In [43]:
american_messages["message_length"] = (
    american_messages["customer_message"]
    .str.split()
    .str.len()
)

american_messages["message_length"].describe()

count    18045.000000
mean        18.666112
std         11.096809
min          2.000000
25%         10.000000
50%         18.000000
75%         25.000000
max         62.000000
Name: message_length, dtype: float64

In [44]:
discovery_sample = american_messages.sample(
    n=100,
    random_state=42
).reset_index(drop=True)

In [45]:
discovery_sample.to_csv(
    "../data/americanair_intent_discovery.csv",
    index=False
)

In [46]:
for i, row in discovery_sample.head(20).iterrows():
    print("\n" + "=" * 80)
    print(f"EXAMPLE {i + 1}")
    print("=" * 80)
    print("CUSTOMER:")
    print(row["customer_message"])
    print("\nAMERICAN AIR:")
    print(row["brand_response"])

================================================================================
EXAMPLE 1
================================================================================
CUSTOMER:
@AmericanAir Not cutting it. You should learn from @115879 ‘s automated responses

AMERICAN AIR:
@504066 We're sorry for the delay. We'll have you in the air as soon as we can and we appreciate your patience.

================================================================================
EXAMPLE 2
================================================================================
CUSTOMER:
@AmericanAir Nah, I'll just post them live thanks #SharingIsCaring

AMERICAN AIR:
@330121 We're happy to help in anyway we can. Please follow and share the details in DMs.

================================================================================
EXAMPLE 3
================================================================================
CUSTOMER:
@AmericanAir Your airport team has been no help. Told me to call customer service instead of rescheduling my flight. Everyone keeps passing the buck.

AMERICAN AIR:
@474024 We're very sorry we weren't able to confirm you on your preferred flight right away. Please continue working with our airport team.

================================================================================
EXAMPLE 4
================================================================================
CUSTOMER:
@AmericanAir Now she has to miss a major 5 figure deal she is needed to be a part of. They weren’t accommodating at all and closed the gate before the 10 Min window.

AMERICAN AIR:
@637533 What's wrong, Camille. We'd like to help if we can.

================================================================================
EXAMPLE 5
================================================================================
CUSTOMER:
@AmericanAir What number can I call

AMERICAN AIR:
@342125 We're unable to refund a ticket for a trip you're taking. Please let us know if we can help in someway.

================================================================================
EXAMPLE 6
================================================================================
CUSTOMER:
@AmericanAir But how can one penalize someone for not filling a seat that they have already paid for?  If anything, they should be reimbursed if their seat is filled by someone else, yes?

AMERICAN AIR:
@641060 It depends on the type of ticket you hold. Please call our folks in Reservations at 800-433-7300 and they'll take a peek at your fare.

================================================================================
EXAMPLE 7
================================================================================
CUSTOMER:
@AmericanAir 👍🏽

AMERICAN AIR:
@186869 Our gate team will make sure everyone is taken great care of. Please let their team know if you have questions.

================================================================================
EXAMPLE 8
================================================================================
CUSTOMER:
@AmericanAir Why a change fee when this was caused by a natural disaster? Since a fire prevented me from going to Santa Rosa, I have to pay $200/ticket? https://t.co/yqNpgrFLY9

AMERICAN AIR:
@542725 We're working with our customers to assist them as best as possible. Please DM your record locator so we can look into this further.

================================================================================
EXAMPLE 9
================================================================================
CUSTOMER:
@AmericanAir Saying sorry is not a solution. Quite disappointed in my first experience with American, could be my last.

AMERICAN AIR:
@783762 We're sorry you're not enjoying yourself, Alex. We always want you to have a great experience with us.

================================================================================
EXAMPLE 10
================================================================================
CUSTOMER:
@AmericanAir For 2 years I have been traveling w @AmericanAir and never get upgraded, I am tired of this. With @delta I was always upgraded.

AMERICAN AIR:
@279772 We always want you up front with us, Selma, and we're so sorry we were unable to upgrade you today.

================================================================================
EXAMPLE 11
================================================================================
CUSTOMER:
@AmericanAir @127032 I’m curious to know what they DMd you???

AMERICAN AIR:
@127032 Please check your DMs for a message.

================================================================================
EXAMPLE 12
================================================================================
CUSTOMER:
@AmericanAir And I understand safety but flight staff acting like it is an inconvenience to answer questions is my main issue.

AMERICAN AIR:
@444007 Safety is our top priority and we apologize for the delay. Our team's preparing as quickly as they can for takeoff.

================================================================================
EXAMPLE 13
================================================================================
CUSTOMER:
@AmericanAir Por todas las redes sociales seguire dia tras dia señalando a @AmericanAir como una compañia poco seria y sinvergüenza

AMERICAN AIR:
@810097 Please continue to work with our baggage folks. Well have you reunited with your bag as soon as possible.

================================================================================
EXAMPLE 14
================================================================================
CUSTOMER:
@AmericanAir And if you don't, then what am I supposed to do? I'm flying out of DFW, which is where WaPo says most of the flights without pilots are. Would appreciate a chance to cancel without penalty rather than hold my breath you'll get it fixed in time.

AMERICAN AIR:
@134908 We know how important the holidays are and fully expect to avoid cancellations during this time, Kristen.

================================================================================
EXAMPLE 15
================================================================================
CUSTOMER:
@AmericanAir Should’ve booked on AA. Rushing to NYC for an urgent meeting and will now miss it thanks to the @JetBlue delay.

AMERICAN AIR:
@318258 Yes, Piyush. AA18 is currently on time.

================================================================================
EXAMPLE 16
================================================================================
CUSTOMER:
@AmericanAir Now a flight from Charlotte 2 SFO that I can’t use my computer because there is no power &amp; can’t watch or listen to anything either.  Bleh!

AMERICAN AIR:
@360958 We have a responsibility to handle every situation with professionalism and we're sorry that you experienced differently today.

================================================================================
EXAMPLE 17
================================================================================
CUSTOMER:
@AmericanAir Least of my worries now. Waiting over an hour for my bag was just unacceptable @AmericanAir

AMERICAN AIR:
@253049 What a bummer. You can check the ending on your next flight if you can wait that long!

================================================================================
EXAMPLE 18
================================================================================
CUSTOMER:
@AmericanAir Sent. Thanks.

AMERICAN AIR:
@623378 We'd be happy to help, David. Can you verify in DMs which record locator this in reference to?

================================================================================
EXAMPLE 19
================================================================================
CUSTOMER:
@AmericanAir Ahhhhh. Noted. Time for me to diet

AMERICAN AIR:
@666652 We do post seat sizes, Stan. Click here to view them on our website. https://t.co/Cqtk8kHZip

================================================================================
EXAMPLE 20
================================================================================
CUSTOMER:
@AmericanAir @188393 Unless they don't, in which case, they won't care.

AMERICAN AIR:
@188393 It's our pleasure to have you fly with us today. Time to sit back, relax and our crew will take great care of you!

In [47]:
for i, message in enumerate(discovery_sample["customer_message"], start=1):
    print(f"{i}. {message}")

1. @AmericanAir Not cutting it. You should learn from @115879 ‘s automated responses
2. @AmericanAir Nah, I'll just post them live thanks #SharingIsCaring
3. @AmericanAir Your airport team has been no help. Told me to call customer service instead of rescheduling my flight. Everyone keeps passing the buck.
4. @AmericanAir Now she has to miss a major 5 figure deal she is needed to be a part of. They weren’t accommodating at all and closed the gate before the 10 Min window.
5. @AmericanAir What number can I call
6. @AmericanAir But how can one penalize someone for not filling a seat that they have already paid for?  If anything, they should be reimbursed if their seat is filled by someone else, yes?
7. @AmericanAir 👍🏽
8. @AmericanAir Why a change fee when this was caused by a natural disaster? Since a fire prevented me from going to Santa Rosa, I have to pay $200/ticket? https://t.co/yqNpgrFLY9
9. @AmericanAir Saying sorry is not a solution. Quite disappointed in my first experience with American, could be my last.
10. @AmericanAir For 2 years I have been traveling w @AmericanAir and never get upgraded, I am tired of this. With @delta I was always upgraded.
11. @AmericanAir @127032 I’m curious to know what they DMd you???
12. @AmericanAir And I understand safety but flight staff acting like it is an inconvenience to answer questions is my main issue.
13. @AmericanAir Por todas las redes sociales seguire dia tras dia señalando a @AmericanAir como una compañia poco seria y sinvergüenza
14. @AmericanAir And if you don't, then what am I supposed to do? I'm flying out of DFW, which is where WaPo says most of the flights without pilots are. Would appreciate a chance to cancel without penalty rather than hold my breath you'll get it fixed in time.
15. @AmericanAir Should’ve booked on AA. Rushing to NYC for an urgent meeting and will now miss it thanks to the @JetBlue delay.
16. @AmericanAir Now a flight from Charlotte 2 SFO that I can’t use my computer because there is no power &amp; can’t watch or listen to anything either.  Bleh!
17. @AmericanAir Least of my worries now. Waiting over an hour for my bag was just unacceptable @AmericanAir
18. @AmericanAir Sent. Thanks.
19. @AmericanAir Ahhhhh. Noted. Time for me to diet
20. @AmericanAir @188393 Unless they don't, in which case, they won't care.
21. @AmericanAir I’m actually flying you guys in a couple weeks see look. I’m very excited https://t.co/ZIxJIRHM6E
22. @AmericanAir Main issue is people who PAID for Priority &amp; ME trying to do YOUR job by keeping Group 9 from boarding but Gate Agent letting them in
23. @AmericanAir Just did. Thank you!
24. @AmericanAir We’re all bronze members friends get priority boarding I don’t very strange. Great Start!!!😡😡😡
25. @AmericanAir Appreciate apologies but was told my bag NEVER left Ohare Mon, now they say it's not here. Not fair for Vets to be treated like this!! HELP
26. @AmericanAir don’t fly @137434 and will now no longer fly with American. Should tell higher ups to reconsider the mode
27. @AmericanAir While I couldn't seem to board an on-time plane today, apparently I'm still better off than my suitcase. #baggageMIA
28. @AmericanAir Seriously - the delays and customer service have gotten worse since the US Airways acquisition. You just got a new loyal customer, @Delta.
29. @AmericanAir The gate lady hooked it up, you’re back on my good side
30. @AmericanAir Okay thanks I responded
31. @AmericanAir Thank you
32. @AmericanAir How can I fly standby if you cancelled my flight?
33. @AmericanAir My wife and I️ will gladly take a first class upgrade on our second leg to make up for it 😬
34. @AmericanAir Yay!
35. @AmericanAir I waited for one for over an hour
36. @AmericanAir Thanks @AmericanAir still waiting on the specific customer contact info for baggage refund
37. @AmericanAir Thanks for apology. From the heart 😕That helps me get home. Maybe instead @116450 @Delta can match my execplat status?
38. @AmericanAir Not what the attendant said.
39. @AmericanAir It's great that you have that desire. What are you doing to get flight 2289 off the ground?
40. @AmericanAir Ive now spent over 5 hours in DFW and am now reboarding...any good faith available? #blindloyalty #goingforgreat #delayedallday
41. @AmericanAir No your gate agent lied so you were not transparent and not most updated info avail. You were delaying to get a back up flight attendant the crew told us.
42. @AmericanAir I️ did, the least you could do is respond  Again, I️ can see where you stand with your customers and how much you value them by this lack of respect and rudeness.
43. @AmericanAir My heroes!!
44. @AmericanAir Your team in St Lucia is not to blame for us getting home or not. It is all about American Airlines in Dallas. This is a headquarters issue. This is squarely on you to take blame and resolve. That's why I complain here and not to the ticket booth.
45. @AmericanAir Can Santa Barbara (SBA) get it's LAX flights back?
46. @AmericanAir Heaven forbid @AmericanAir actually provides contact info to a living breathing thinking human being.
47. @AmericanAir What's DM?
48. @AmericanAir Nope still waiting!  But at least we got air now!
49. @AmericanAir Well your crew is inconsistent. Thank you for this information I will be sure to NEVER fly @americanair ever again as every other airline allows economy passengers a carry on item
50. @AmericanAir Doesn’t say that on ur link.
51. @AmericanAir I'll be happy as long as they new young planes are all atleast 737s.

These CJ900s should all be sent to the junkyard. https://t.co/M9yJP5HTpS
52. @AmericanAir Yes, you could not make me pay twice for the same ticket
53. @AmericanAir Took a while but got there in the end! Thanks twitter team you never gave up on me, you take a lot of flack every day but you are amazing!🌟
54. @AmericanAir I've tried to call 3 times now but am continuously being placed on long holds
55. @AmericanAir I encourage your lounge department to look at a map and see that Trinidad is further south than the islands off Venezuela, which qualifies
56. @AmericanAir We did,they hung up on my husband #overbooked #overbooking #americanairlines #worstairline #airline #airlines they dont care about customers
57. @AmericanAir Traveling* but noted. Thanks!
58. @AmericanAir Thank you.  I wouldn't be so upset but they didn't allow her to bring her carry on board and charged her on the return?? Conf #FURNDK Tks.
59. @AmericanAir 3k7wd56, you can check.  I wouldn’t complain if this wasn’t 100% a bad gate agent. I expect better.
60. .@AmericanAir please update planes to at least 2007 level.  Your fleet is awful - should charge econo prices with your econo planes
61. @AmericanAir Well, it didn't but I still was forced to check it. But thanks for the super helpful link, now I'll definitely not be late for the wedding 😐
62. @AmericanAir Also, people paid extra for exit row - and what do they get???
63. @AmericanAir what are you going to do to compensate me- first class seat that doesn’t work? On a red-eye?
64. @AmericanAir I appreciate it but please don't try to pacify me with a canned response. I don't have her name but please take action ☹️
65. @AmericanAir This feels like a deliberate ploy to charge ppl fee's when they done their due diligence to check in on time.
66. @AmericanAir @AmericanAir AA customer service has a bad attitude and not willing to help. Been waiting 1.5 hours for luggage. #flyunited
67. @AmericanAir Sadly not. You’ve moved us to another gate and there’s no sign of the plane still, so definitely going to miss the game now
68. @AmericanAir DM sent.
69. @AmericanAir @209254 Give him a tissue 😂😂
70. @AmericanAir Sent
71. @AmericanAir Nope. Roads won't be open until tomorrow. Was forced to buy a new ticket. You lost a customer today.
72. @AmericanAir Still no first officer any one know why this has now delayed us from 6:45 until never ever land?
73. @AmericanAir Things happen but what makes a company great is their customer service, which is clearly lacking at #AmericanAirlines
74. @AmericanAir They did try to work with customer service. Even a supervisor. They were told they were on their own
75. @AmericanAir Bot
76. @AmericanAir I did last night. Lost item ID 6964514
77. @AmericanAir That's not how you treat customers especially when you have a PR crisis like you have
78. @AmericanAir The fact that I got a twitter response faster than I could talk to an agent at one of your biggest hubs says it all. Thanks!
79. @AmericanAir They took good care - Maintenance fixed it - thx
80. @AmericanAir There are no American employees here at airport.
81. @AmericanAir Zvbetr just spent 15 minutes with customer service
82. @AmericanAir Just landed.  Another horrible AA flight.  Cabin went from 66 degrees up to 84.  Waking all up.  Flight attndt could barely fit down aisle
83. @AmericanAir @250991 Yeah, why wouldn’t you want to hear about 25,000 free miles just for signing up, while you’re strapped to a seat with nowhere to run?!?!
84. @AmericanAir Going and returning had to request seats together from tkt agent. Why not assigned together from the get go?
85. @AmericanAir I respectfully again request now a refund of $100. @AmericanAir #AmericanAirlines
86. @AmericanAir Those confirmed upgrades didn’t come through? Oh wait. You lied. Will you publicly admit that or should I post by boarding pass?
87. @AmericanAir You are free to DM me
88. @AmericanAir Cool. So Cathay says it’s you, and you say it’s Cathay. Glad you guys are “working together behind the scenes” for us.... #honeymoonhell
89. @AmericanAir Thanks guys will send you now.
90. @AmericanAir This link has already been shared with me and I’m stating that AA has additional policy that is not listed apparently. Also why would the website list a same day change option that violates policy, and policy that is not published.
91. @AmericanAir I will never fly @AmericanAir again.
92. @AmericanAir I've done that. I now want to complain to YOUR company about their relationship with Citi. You shouldn't be working with a company that is so dismissive of their customers.
93. @AmericanAir @508852 Ohh my god!! :)
94. @AmericanAir This would be for a trip tomorrow 10/17. An urgent situation. Just thought using ya’ll as my preferred airline was worth something
95. @AmericanAir I'm most likely going to loss my connection for this....... this is so unacceptable. Wish I could've gone with JetBlue.
96. @AmericanAir @214512 Yeah, talk to them in DM cause they don’t want the whole world knowing how bad they screwed you over.
97. @AmericanAir #thankyou
98. @AmericanAir @537770 Bruh they delayed my flight 2hrs today. I won’t be flying with them again😂
99. @AmericanAir Do I have guaranteed seat on flight 3059 ? Record Locator is ZKZEFU
100. @AmericanAir 140, 150... I fell asleep... Currently 235 but the odds of us making that don't look good.

In [48]:
discovery_sample["rough_intent"] = ""

In [49]:
discovery_sample[
    ["customer_message", "rough_intent"]
].head(20)

                                     customer_message rough_intent
0   @AmericanAir Not cutting it. You should learn ...
1   @AmericanAir Nah, I'll just post them live tha...
2   @AmericanAir Your airport team has been no hel...
3   @AmericanAir Now she has to miss a major 5 fig...
4                 @AmericanAir What number can I call
5   @AmericanAir But how can one penalize someone ...
6                                     @AmericanAir 👍🏽
7   @AmericanAir Why a change fee when this was ca...
8   @AmericanAir Saying sorry is not a solution. Q...
9   @AmericanAir For 2 years I have been traveling...
10  @AmericanAir @127032 I’m curious to know what ...
11  @AmericanAir And I understand safety but fligh...
12  @AmericanAir Por todas las redes sociales segu...
13  @AmericanAir And if you don't, then what am I ...
14  @AmericanAir Should’ve booked on AA. Rushing t...
15  @AmericanAir Now a flight from Charlotte 2 SFO...
16  @AmericanAir Least of my worries now. Waiting ...
17                         @AmericanAir Sent. Thanks.
18    @AmericanAir Ahhhhh. Noted. Time for me to diet
19  @AmericanAir @188393 Unless they don't, in whi...

In [50]:
for i, message in enumerate(discovery_sample["customer_message"].head(20), start=1):
    print(f"\n{i}. {message}")

1. @AmericanAir Not cutting it. You should learn from @115879 ‘s automated responses

2. @AmericanAir Nah, I'll just post them live thanks #SharingIsCaring

3. @AmericanAir Your airport team has been no help. Told me to call customer service instead of rescheduling my flight. Everyone keeps passing the buck.

4. @AmericanAir Now she has to miss a major 5 figure deal she is needed to be a part of. They weren’t accommodating at all and closed the gate before the 10 Min window.

5. @AmericanAir What number can I call

6. @AmericanAir But how can one penalize someone for not filling a seat that they have already paid for?  If anything, they should be reimbursed if their seat is filled by someone else, yes?

7. @AmericanAir 👍🏽

8. @AmericanAir Why a change fee when this was caused by a natural disaster? Since a fire prevented me from going to Santa Rosa, I have to pay $200/ticket? https://t.co/yqNpgrFLY9

9. @AmericanAir Saying sorry is not a solution. Quite disappointed in my first experience with American, could be my last.

10. @AmericanAir For 2 years I have been traveling w @AmericanAir and never get upgraded, I am tired of this. With @delta I was always upgraded.

11. @AmericanAir @127032 I’m curious to know what they DMd you???

12. @AmericanAir And I understand safety but flight staff acting like it is an inconvenience to answer questions is my main issue.

13. @AmericanAir Por todas las redes sociales seguire dia tras dia señalando a @AmericanAir como una compañia poco seria y sinvergüenza

14. @AmericanAir And if you don't, then what am I supposed to do? I'm flying out of DFW, which is where WaPo says most of the flights without pilots are. Would appreciate a chance to cancel without penalty rather than hold my breath you'll get it fixed in time.

15. @AmericanAir Should’ve booked on AA. Rushing to NYC for an urgent meeting and will now miss it thanks to the @JetBlue delay.

16. @AmericanAir Now a flight from Charlotte 2 SFO that I can’t use my computer because there is no power &amp; can’t watch or listen to anything either.  Bleh!

17. @AmericanAir Least of my worries now. Waiting over an hour for my bag was just unacceptable @AmericanAir

18. @AmericanAir Sent. Thanks.

19. @AmericanAir Ahhhhh. Noted. Time for me to diet

20. @AmericanAir @188393 Unless they don't, in which case, they won't care.

In [51]:
for i, message in enumerate(
    discovery_sample["customer_message"].iloc[20:40],
    start=21
):
    print(f"\n{i}. {message}")

21. @AmericanAir I’m actually flying you guys in a couple weeks see look. I’m very excited https://t.co/ZIxJIRHM6E

22. @AmericanAir Main issue is people who PAID for Priority &amp; ME trying to do YOUR job by keeping Group 9 from boarding but Gate Agent letting them in

23. @AmericanAir Just did. Thank you!

24. @AmericanAir We’re all bronze members friends get priority boarding I don’t very strange. Great Start!!!😡😡😡

25. @AmericanAir Appreciate apologies but was told my bag NEVER left Ohare Mon, now they say it's not here. Not fair for Vets to be treated like this!! HELP

26. @AmericanAir don’t fly @137434 and will now no longer fly with American. Should tell higher ups to reconsider the mode

27. @AmericanAir While I couldn't seem to board an on-time plane today, apparently I'm still better off than my suitcase. #baggageMIA

28. @AmericanAir Seriously - the delays and customer service have gotten worse since the US Airways acquisition. You just got a new loyal customer, @Delta.

29. @AmericanAir The gate lady hooked it up, you’re back on my good side

30. @AmericanAir Okay thanks I responded

31. @AmericanAir Thank you

32. @AmericanAir How can I fly standby if you cancelled my flight?

33. @AmericanAir My wife and I️ will gladly take a first class upgrade on our second leg to make up for it 😬

34. @AmericanAir Yay!

35. @AmericanAir I waited for one for over an hour

36. @AmericanAir Thanks @AmericanAir still waiting on the specific customer contact info for baggage refund

37. @AmericanAir Thanks for apology. From the heart 😕That helps me get home. Maybe instead @116450 @Delta can match my execplat status?

38. @AmericanAir Not what the attendant said.

39. @AmericanAir It's great that you have that desire. What are you doing to get flight 2289 off the ground?

40. @AmericanAir Ive now spent over 5 hours in DFW and am now reboarding...any good faith available? #blindloyalty #goingforgreat #delayedallday

In [52]:
for i, message in enumerate(
    discovery_sample["customer_message"].iloc[40:100],
    start=41
):
    print(f"\n{i}. {message}")

41. @AmericanAir No your gate agent lied so you were not transparent and not most updated info avail. You were delaying to get a back up flight attendant the crew told us.

42. @AmericanAir I️ did, the least you could do is respond  Again, I️ can see where you stand with your customers and how much you value them by this lack of respect and rudeness.

43. @AmericanAir My heroes!!

44. @AmericanAir Your team in St Lucia is not to blame for us getting home or not. It is all about American Airlines in Dallas. This is a headquarters issue. This is squarely on you to take blame and resolve. That's why I complain here and not to the ticket booth.

45. @AmericanAir Can Santa Barbara (SBA) get it's LAX flights back?

46. @AmericanAir Heaven forbid @AmericanAir actually provides contact info to a living breathing thinking human being.

47. @AmericanAir What's DM?

48. @AmericanAir Nope still waiting!  But at least we got air now!

49. @AmericanAir Well your crew is inconsistent. Thank you for this information I will be sure to NEVER fly @americanair ever again as every other airline allows economy passengers a carry on item

50. @AmericanAir Doesn’t say that on ur link.

51. @AmericanAir I'll be happy as long as they new young planes are all atleast 737s.

These CJ900s should all be sent to the junkyard. https://t.co/M9yJP5HTpS

52. @AmericanAir Yes, you could not make me pay twice for the same ticket

53. @AmericanAir Took a while but got there in the end! Thanks twitter team you never gave up on me, you take a lot of flack every day but you are amazing!🌟

54. @AmericanAir I've tried to call 3 times now but am continuously being placed on long holds

55. @AmericanAir I encourage your lounge department to look at a map and see that Trinidad is further south than the islands off Venezuela, which qualifies

56. @AmericanAir We did,they hung up on my husband #overbooked #overbooking #americanairlines #worstairline #airline #airlines they dont care about customers

57. @AmericanAir Traveling* but noted. Thanks!

58. @AmericanAir Thank you.  I wouldn't be so upset but they didn't allow her to bring her carry on board and charged her on the return?? Conf #FURNDK Tks.

59. @AmericanAir 3k7wd56, you can check.  I wouldn’t complain if this wasn’t 100% a bad gate agent. I expect better.

60. .@AmericanAir please update planes to at least 2007 level.  Your fleet is awful - should charge econo prices with your econo planes

61. @AmericanAir Well, it didn't but I still was forced to check it. But thanks for the super helpful link, now I'll definitely not be late for the wedding 😐

62. @AmericanAir Also, people paid extra for exit row - and what do they get???

63. @AmericanAir what are you going to do to compensate me- first class seat that doesn’t work? On a red-eye?

64. @AmericanAir I appreciate it but please don't try to pacify me with a canned response. I don't have her name but please take action ☹️

65. @AmericanAir This feels like a deliberate ploy to charge ppl fee's when they done their due diligence to check in on time.

66. @AmericanAir @AmericanAir AA customer service has a bad attitude and not willing to help. Been waiting 1.5 hours for luggage. #flyunited

67. @AmericanAir Sadly not. You’ve moved us to another gate and there’s no sign of the plane still, so definitely going to miss the game now

68. @AmericanAir DM sent.

69. @AmericanAir @209254 Give him a tissue 😂😂

70. @AmericanAir Sent

71. @AmericanAir Nope. Roads won't be open until tomorrow. Was forced to buy a new ticket. You lost a customer today.

72. @AmericanAir Still no first officer any one know why this has now delayed us from 6:45 until never ever land?

73. @AmericanAir Things happen but what makes a company great is their customer service, which is clearly lacking at #AmericanAirlines

74. @AmericanAir They did try to work with customer service. Even a supervisor. They were told they were on their own

75. @AmericanAir Bot

76. @AmericanAir I did last night. Lost item ID 6964514

77. @AmericanAir That's not how you treat customers especially when you have a PR crisis like you have

78. @AmericanAir The fact that I got a twitter response faster than I could talk to an agent at one of your biggest hubs says it all. Thanks!

79. @AmericanAir They took good care - Maintenance fixed it - thx

80. @AmericanAir There are no American employees here at airport.

81. @AmericanAir Zvbetr just spent 15 minutes with customer service

82. @AmericanAir Just landed.  Another horrible AA flight.  Cabin went from 66 degrees up to 84.  Waking all up.  Flight attndt could barely fit down aisle

83. @AmericanAir @250991 Yeah, why wouldn’t you want to hear about 25,000 free miles just for signing up, while you’re strapped to a seat with nowhere to run?!?!

84. @AmericanAir Going and returning had to request seats together from tkt agent. Why not assigned together from the get go?

85. @AmericanAir I respectfully again request now a refund of $100. @AmericanAir #AmericanAirlines

86. @AmericanAir Those confirmed upgrades didn’t come through? Oh wait. You lied. Will you publicly admit that or should I post by boarding pass?

87. @AmericanAir You are free to DM me

88. @AmericanAir Cool. So Cathay says it’s you, and you say it’s Cathay. Glad you guys are “working together behind the scenes” for us.... #honeymoonhell

89. @AmericanAir Thanks guys will send you now.

90. @AmericanAir This link has already been shared with me and I’m stating that AA has additional policy that is not listed apparently. Also why would the website list a same day change option that violates policy, and policy that is not published.

91. @AmericanAir I will never fly @AmericanAir again.

92. @AmericanAir I've done that. I now want to complain to YOUR company about their relationship with Citi. You shouldn't be working with a company that is so dismissive of their customers.

93. @AmericanAir @508852 Ohh my god!! :)

94. @AmericanAir This would be for a trip tomorrow 10/17. An urgent situation. Just thought using ya’ll as my preferred airline was worth something

95. @AmericanAir I'm most likely going to loss my connection for this....... this is so unacceptable. Wish I could've gone with JetBlue.

96. @AmericanAir @214512 Yeah, talk to them in DM cause they don’t want the whole world knowing how bad they screwed you over.

97. @AmericanAir #thankyou

98. @AmericanAir @537770 Bruh they delayed my flight 2hrs today. I won’t be flying with them again😂

99. @AmericanAir Do I have guaranteed seat on flight 3059 ? Record Locator is ZKZEFU

100. @AmericanAir 140, 150... I fell asleep... Currently 235 but the odds of us making that don't look good.

In [ ]:
# Intent Discovery — AmericanAir

## Purpose

I manually inspected a random sample of 100 customer-to-AmericanAir interactions to understand the types of requests, complaints, follow-ups, and noise present in the dataset.

The goal of this stage was not to define the final taxonomy immediately, but to identify recurring customer goals and understand the ambiguity and noise in the real-world data.

The sample was drawn using a fixed random seed (`random_state=42`) from the AmericanAir customer-to-brand interactions.

---

## Initial observations

The sample contains a mixture of:

- Genuine customer support requests
- Complaints about service quality
- Follow-ups to existing conversations
- Requests involving multiple topics
- Simple acknowledgements or thank-you messages
- Social/reactional messages
- Ambiguous or low-information messages

This means that not every incoming tweet should necessarily be forced into a support intent.

For example:

- "What number can I call" represents a clear support request.
- "How can I fly standby if you cancelled my flight?" contains a clear actionable request.
- "Sent. Thanks." is an acknowledgement rather than a support request.
- "👍🏽" contains no actionable support request.
- "I'm still waiting..." may represent a follow-up to an existing case rather than a new support issue.

---

## Message-type observations

During manual inspection, I observed the following broad message types:

### 1. Support requests

Messages where the customer is asking AmericanAir to provide information, solve a problem, or take some action.

Examples observed:

- Asking how to fly standby after a cancelled flight.
- Asking for a contact number.
- Asking about a flight.
- Asking for a refund or compensation.
- Asking about changing or cancelling travel plans.

### 2. Complaints

Messages primarily expressing dissatisfaction with AmericanAir, its staff, policies, delays, or service.

Examples observed:

- Complaints about poor customer service.
- Complaints about gate agents.
- Complaints about delays.
- Complaints about baggage handling.
- Complaints about aircraft or onboard conditions.

A complaint can still contain an actionable support intent. Therefore, complaint should not automatically become the customer's primary intent.

### 3. Follow-ups / existing cases

Messages indicating that the customer is continuing an existing support interaction.

Examples observed:

- "I responded."
- "DM sent."
- "Still waiting."
- "Not what the attendant said."
- Asking what was sent in a previous DM.

These messages may require different handling from a new support request because the necessary context may exist in an earlier conversation.

### 4. Thanks / acknowledgement

Messages such as:

- "Thank you"
- "Just did. Thank you!"
- "Sent. Thanks."
- "#thankyou"

These do not represent a new customer support intent.

### 5. Unclear / social / low-information messages

Some tweets contain very little actionable information.

Examples include:

- "👍🏽"
- "Yay!"
- "Ahhhhh. Noted."
- General expressions of excitement about flying.
- Statements directed at other users rather than a direct support request.

These should not be artificially assigned to a domain intent.

---

# Candidate Support Topics

The following candidate topics repeatedly appeared during the manual inspection.

## 1. Flight disruption

Includes situations involving:

- Flight delays
- Flight cancellations
- Missed connections
- Reboarding
- Missing crew
- Gate-related disruption
- Operational delays
- Requests for alternative arrangements after disruption

Examples from the discovery sample include:

- Example 14 — customer wants to cancel without penalty because of expected flight disruption.
- Example 32 — customer asks about standby after a cancelled flight.
- Example 40 — customer has spent several hours at DFW and asks about compensation.
- Example 72 — customer is waiting for a first officer and experiencing a major delay.
- Example 95 — customer expects to miss a connection because of a delay.
- Example 100 — customer is concerned about making a flight because of delays.

---

## 2. Baggage

Includes:

- Missing baggage
- Delayed baggage
- Baggage tracking
- Baggage-related complaints
- Baggage fees
- Baggage refunds or compensation

Examples:

- Example 17 — customer has been waiting for a bag.
- Example 25 — customer says the bag is missing.
- Example 27 — customer compares a flight delay with a missing suitcase.
- Example 36 — customer is waiting for information regarding a baggage refund.
- Example 66 — customer has been waiting for luggage.

---

## 3. Booking / itinerary changes

Includes requests or problems involving:

- Changing a flight
- Cancelling a flight
- Rescheduling
- Same-day changes
- Changing travel plans
- Avoiding cancellation/change penalties

Examples:

- Example 3 — customer wants to reschedule a flight.
- Example 8 — customer questions a change fee after a natural disaster.
- Example 14 — customer wants to cancel without penalty.
- Example 90 — customer questions the same-day change policy.
- Example 94 — customer has an urgent trip the following day.

---

## 4. Seats / seat assignment

Includes:

- Seat assignment problems
- Paid seat issues
- Seats not being together
- Exit-row seats
- Seat availability
- Requests for seat changes

Examples:

- Example 6 — customer complains about a paid seat being reassigned.
- Example 62 — customer questions what they receive after paying for exit-row seats.
- Example 63 — customer complains about a first-class seat not working.
- Example 84 — customers had to request seats together.
- Example 99 — customer asks whether they have a guaranteed seat.

---

## 5. Upgrades / loyalty benefits

Includes:

- First-class upgrades
- Upgrade eligibility
- Priority boarding
- Loyalty status
- Status matching
- Loyalty benefits

Examples:

- Example 10 — customer complains about never receiving upgrades.
- Example 22 — customer complains about Priority boarding.
- Example 24 — customer questions priority boarding eligibility.
- Example 33 — customer requests a first-class upgrade.
- Example 37 — customer asks about Delta matching their status.
- Example 86 — customer says confirmed upgrades did not come through.

---

## 6. Fees / charges

Includes:

- Change fees
- Baggage fees
- Duplicate charges
- Unexpected charges
- Questions about penalties or fees

Examples:

- Example 8 — customer questions a $200 change fee.
- Example 52 — customer does not want to pay twice for the same ticket.
- Example 58 — customer complains about being charged for baggage.
- Example 65 — customer believes a fee was improperly charged.
- Example 85 — customer requests a refund.

---

## 7. Refunds / compensation

Includes requests for:

- Refunds
- Compensation after disruption
- Reimbursement
- Goodwill compensation

Examples:

- Example 36 — baggage refund.
- Example 40 — asks whether goodwill compensation is available.
- Example 63 — asks what AmericanAir will do to compensate them.
- Example 85 — explicitly requests a refund.

This category may overlap with fees, baggage, and flight disruption, so the boundary will need to be defined during taxonomy refinement.

---

## 8. Flight information / status

Includes requests for information about:

- Flight status
- Flight operation
- Flight schedules
- Whether a particular flight will operate
- Whether a customer has a confirmed seat

Examples:

- Example 39 — asks what is happening with flight 2289.
- Example 45 — asks about the return of a particular route.
- Example 72 — asks why the flight is delayed.
- Example 99 — asks about a guaranteed seat on flight 3059.

---

## 9. Airport / gate / staff issues

Includes problems involving:

- Gate agents
- Airport staff
- Boarding process
- Airport customer service
- Gate closures
- Airport-level assistance

Examples:

- Example 3 — customer complains about the airport team.
- Example 4 — gate was closed before the customer could board.
- Example 12 — complaint about flight staff.
- Example 41 — customer says the gate agent provided misleading information.
- Example 44 — complaint about the handling of the issue at Dallas headquarters.
- Example 56 — customer says airport/customer service did not help.
- Example 74 — customer says airport staff and supervisors did not help.

This topic may overlap heavily with flight disruption and boarding issues.

---

## 10. Onboard experience / aircraft issues

Includes:

- Power/electrical problems
- Cabin temperature
- Aircraft condition
- In-flight equipment
- Entertainment
- General onboard experience

Examples:

- Example 16 — no power available to use a computer or entertainment.
- Example 51 — complaint about aircraft type.
- Example 60 — complaint about aircraft/fleet condition.
- Example 79 — maintenance fixed an issue.
- Example 82 — complaint about cabin temperature and aisle conditions.

---

## 11. Contact / customer-service access

Includes requests or complaints involving:

- Contact information
- Phone support
- Difficulty reaching an agent
- Long telephone holds
- Requests to communicate privately through DM

Examples:

- Example 5 — asks what number to call.
- Example 46 — complains about lack of human contact information.
- Example 47 — asks what DM means.
- Example 54 — repeatedly placed on hold.
- Example 78 — compares Twitter response time with phone support.

---

# Important taxonomy observations

Several candidate topics overlap.

For example:

### Flight disruption vs. compensation

> "I've been delayed for five hours. Is there any good faith available?"

This contains both a disruption and a compensation request.

### Baggage vs. refund

> "Still waiting on the specific customer contact info for baggage refund."

This contains both baggage and refund.

### Airport issue vs. flight disruption

> "The gate agent lied and delayed us while waiting for another flight attendant."

This contains both an operational disruption and a complaint about airport staff.

Therefore, the final taxonomy should define a **primary-intent rule** rather than assigning multiple labels whenever possible.

---

# Preliminary Primary-Intent Rule

For the first taxonomy iteration, the primary intent should represent:

> **The customer's main actionable goal — what they want AmericanAir to help them accomplish.**

The emotional tone of the message should not determine the intent.

For example:

- "Your service is terrible. Where is my luggage?" → Baggage
- "I'm furious about the delay. Can I get a refund?" → Refund/compensation
- "Your gate agent was useless. Can you reschedule me?" → Booking/change
- "Thanks, I responded." → Follow-up/acknowledgement rather than a domain support intent

This rule will be tested and refined against additional examples before the final taxonomy is frozen.

---

# What I will not treat as a support intent

The following should not automatically become domain intents:

- Thanks / acknowledgement
- Generic praise
- Social reactions
- Messages with no actionable request
- Existing-case follow-ups when no new support goal is expressed
- Completely ambiguous messages

These cases may instead be handled by a separate message-type or routing layer.

---

# Next step

The candidate topics identified from the 100-example discovery sample are:

1. Flight disruption
2. Baggage
3. Booking / itinerary changes
4. Seats / seat assignment
5. Upgrades / loyalty benefits
6. Fees / charges
7. Refunds / compensation
8. Flight information / status
9. Airport / gate / staff issues
10. Onboard experience / aircraft issues
11. Contact / customer-service access

These are **candidate categories, not the final taxonomy**.

The next stage is to test these candidates against a larger sample and determine which categories should be:

- Kept as separate intents
- Merged
- Removed because they are too rare
- Treated as routing/handling conditions rather than intents
- Split because they contain meaningfully different customer goals

In [53]:
discovery_ids = set(discovery_sample["customer_tweet_id"])

taxonomy_validation = american_messages[
    ~american_messages["customer_tweet_id"].isin(discovery_ids)
].sample(
    n=200,
    random_state=123
).reset_index(drop=True)

In [54]:
taxonomy_validation.shape

(200, 4)

In [55]:
for i, message in enumerate(
    taxonomy_validation["customer_message"].iloc[:25],
    start=1
):
    print(f"\n{i}. {message}")

1. @AmericanAir I have been on the phone twice for 3 hours with Travelocity. No results. $400 fee to cancel flight to island with no power. Told #hopeless

2. @AmericanAir Can I add the trip insurance after purchasing my ticket

3. @AmericanAir I DMd you

4. @AmericanAir Will do, thanks!

5. @AmericanAir There is no one at the counters at this airport. Any suggestions?

6. @AmericanAir Got the flight and your gate woman was nothing but rude and told me when I asked for help she told me to do it myself.  Is this typical?

7. @AmericanAir have you heard of any updates?

8. @AmericanAir Glad to fly @AmericanAir 🛫

9. @AmericanAir I asked but FA didn’t know anything about the Casper promo. Is it supposed to be Casper branded?

10. @AmericanAir LOL. Yep not worth the money paid. Did me no good since agent called 4 &amp; 5 At same time. #wastedmoney

11. @AmericanAir I can no longer make the flight I originally booked. Instead of just letting me give up my seat and get a new flight I'm being charged a fee

12. @AmericanAir The aircraft was a piece of ... work. 😉. No lav, delayed 15 min on taxiway and on landing, this falls on my head. #buynewplanes https://t.co/BeZZtwGJjM

13. @AmericanAir my record locator was BXMKZI

14. @AmericanAir Might be mindful that some took @115873 to airport and there’s no guarantee there will be an Uber option because it’s 11 PM on Tuesday in IND

15. @AmericanAir I was one of the first zones on the plane??? Your tweet makes no sense...kind of like your airline #badairline

16. @AmericanAir Well I had to pay for luggage but should not have. My TSA pre was not recognized on Hawaiian Airlines so I almost missed that fight. And I paid for exit row seats and did not get them with this change. What can you do?

17. @AmericanAir @341052 Good luck - given delay you should get a partial refund and food vouchers. Ridiculous if they don't do that for you.

18. @AmericanAir Beyond thankful for this because of the military families

19. @AmericanAir Hence asking to space my name because it is spaced, which is why I have called for the last 6 months. I didn’t have to before that time.

20. @AmericanAir I very much doubt it.

21. @AmericanAir Very small bags. The issue was section 9. Must pay to check. In real!  My two small bags would have easily fit under my seat.

22. @AmericanAir They have tried repeatedly.

23. @AmericanAir I have TSA precheck, it took physically less than two minutes for me to get to my gate (I'm in Wichita, there are like 4 gates). I watched people get on the flight I was scheduled for

24. @AmericanAir Seems the technical glitch was fixed and was able to check in online while in line.  Feeling bad for others still stuck.

25. @AmericanAir Thanks @AmericanAir! His name is Karan Patel!! :-)

In [61]:
# Taxonomy Validation — AmericanAir

## Purpose

I tested the initial candidate taxonomy against 25 previously unseen AmericanAir customer messages.

The purpose of this validation was to determine:

- Whether the candidate intents cover common customer requests.
- Whether different intents are clearly distinguishable.
- Where multiple intents appear in the same message.
- Which messages cannot be reliably classified using the current taxonomy.
- Whether additional intents are required before creating the final Golden Set.

The validation sample was drawn from AmericanAir customer-to-brand interactions that were not included in the original 100-message discovery sample.

---

## Candidate taxonomy

The initial candidate taxonomy consisted of:

- `flight_disruption`
- `baggage`
- `booking_change`
- `seat`
- `loyalty_upgrade`
- `fees_charges`
- `refund_compensation`
- `flight_information`
- `airport_gate_staff`
- `onboard_aircraft`
- `contact_support`
- `follow_up`
- `non_support`
- `other_unclear`

---

## Labeling rule

The primary intent represents the customer's main actionable goal.

When a message contains multiple issues, I select the intent corresponding to the customer's primary actionable request rather than assigning multiple domain intents.

The emotional tone of a message does not determine its intent.

For example:

- A customer can be angry but still have a `baggage` intent.
- A customer can complain about a delay while primarily requesting a `refund_compensation`.
- A customer can mention a fee while primarily requesting a `booking_change`.

Messages that do not contain a meaningful support request are classified as `non_support`, `follow_up`, or `other_unclear` depending on their role in the conversation.

---

# Validation Results — Examples 1–25

| # | Primary intent | Confidence | Notes |
|---:|---|---|---|
| 1 | `booking_change` | medium | Customer wants to cancel a flight; the $400 fee is an additional issue. |
| 2 | `other_unclear` | high | Trip insurance request is not represented by the current taxonomy. |
| 3 | `follow_up` | high | Customer indicates that they have sent a DM as part of an existing interaction. |
| 4 | `non_support` | high | Acknowledgement with no new support request. |
| 5 | `airport_gate_staff` | high | Customer is asking for help because no staff are available at the airport counters. |
| 6 | `airport_gate_staff` | high | Complaint and request related to the behavior of a gate agent. |
| 7 | `other_unclear` | low | Customer asks for an update but the subject of the update is not clear from the message. |
| 8 | `non_support` | high | Positive social statement with no support request. |
| 9 | `other_unclear` | high | Promotion/product question is not represented by the current taxonomy. |
| 10 | `other_unclear` | low | Context is insufficient to determine the underlying support intent. |
| 11 | `booking_change` | high | Customer wants to give up the original flight and obtain a new flight; the fee is part of the problem. |
| 12 | `onboard_aircraft` | medium | Primary complaint concerns aircraft facilities/condition, although a short delay is also mentioned. |
| 13 | `other_unclear` | medium | Customer only provides a record locator without stating the support goal. |
| 14 | `other_unclear` | medium | Transportation/Uber availability issue does not fit the current taxonomy clearly. |
| 15 | `loyalty_upgrade` | medium | Appears related to boarding-zone/priority treatment, but the exact customer request is unclear. |
| 16 | `fees_charges` | medium | Customer disputes baggage charges and also reports a paid exit-row seat not being provided. Multiple intents are present. |
| 17 | `refund_compensation` | high | Explicit recommendation/request for partial refund and food vouchers following a delay. |
| 18 | `non_support` | high | Positive acknowledgement with no actionable support request. |
| 19 | `other_unclear` | high | Customer is requesting a name-format/account-information change, which is not represented in the current taxonomy. |
| 20 | `non_support` | high | No actionable support request. |
| 21 | `baggage` | high | Customer is disputing baggage/check-in charges and baggage size requirements. |
| 22 | `follow_up` | medium | Appears to be a continuation of an existing support interaction, but context is limited. |
| 23 | `flight_disruption` | low | Customer appears to have missed/been unable to board a scheduled flight, but the exact cause and request are unclear. |
| 24 | `other_unclear` | high | Online check-in/technical glitch is the main issue, but a dedicated `check_in` intent does not currently exist. |
| 25 | `non_support` | high | Thank-you message with no new support request. |

---

# Taxonomy Gaps and Ambiguities

The validation sample revealed several limitations in the initial taxonomy.

## 1. Check-in is missing

Examples involving online check-in or check-in-related technical problems do not fit naturally into the existing taxonomy.

Example:

> Example 24 — customer reports that a technical glitch affected online check-in.

Potential new intent:

`check_in`

---

## 2. Insurance is missing

Example 2 asks whether trip insurance can be added after purchasing a ticket.

This represents a legitimate travel-support request but does not fit naturally into booking changes, fees, or flight information.

Potential new intent:

`insurance`

---

## 3. Promotions are missing

Example 9 concerns a Casper promotion and whether the promotion is branded correctly.

This suggests that promotional/offer-related questions may need their own category if they occur frequently enough in the broader dataset.

Potential new intent:

`promotions`

---

## 4. Account/customer-information requests are missing

Example 19 concerns the formatting of the customer's name.

This does not fit naturally into booking changes or flight information.

Potential new intent:

`account_information`

---

## 5. Transportation assistance may be outside the intended scope

Example 14 discusses whether an Uber option will be available.

This may be part of a broader travel-support issue but does not clearly belong to an AmericanAir-specific support intent.

This should be investigated on a larger sample before adding a dedicated category.

---

## 6. Multiple intents occur frequently

Some messages contain several legitimate issues.

For example, Example 16 contains:

- Baggage fee dispute
- TSA/precheck issue
- Paid exit-row seat problem

The taxonomy therefore requires a consistent primary-intent rule.

For this project, the selected rule is:

> Choose the customer's main actionable goal rather than assigning every topic mentioned in the message.

---

## 7. Context-dependent messages are common

Examples such as:

- "I DMd you"
- "They have tried repeatedly."
- "Have you heard of any updates?"
- "My record locator was BXMKZI"

cannot always be understood from the individual tweet alone.

This is important because the original dataset contains multi-turn conversations.

A production support agent should therefore consider available conversation history rather than relying only on a single tweet.

---

# Preliminary Taxonomy Decision

Based on this validation sample, the initial taxonomy should **not yet be frozen**.

The validation suggests that the following additional intents should be investigated:

- `check_in`
- `insurance`
- `promotions`
- `account_information`

At the same time, some existing categories may overlap and require further testing:

- `flight_disruption` vs. `airport_gate_staff`
- `fees_charges` vs. `refund_compensation`
- `flight_disruption` vs. `flight_information`
- `loyalty_upgrade` vs. boarding-related issues

The next step is to test the revised taxonomy on another unseen sample before freezing the final intent taxonomy.

---

# Next Step

The candidate taxonomy will be revised based on the observed gaps and then evaluated on another unseen batch of customer messages.

The final taxonomy will be frozen only after the revised categories provide reasonable coverage and the major sources of ambiguity have been documented.

The Golden Set will be created only after the taxonomy and labeling guidelines have been finalized.

SyntaxError: unterminated string literal (detected at line 42) (60468016.py, line 42)

In [ ]:
# Taxonomy v2 Validation — Examples 26–50

| # | Primary intent | Confidence | Notes |
|---:|---|---|---|
| 26 | onboard_aircraft | high | Complaint/comment about food quality and taste onboard the aircraft. |
| 27 | other_unclear | high | Website UI/content feedback rather than a defined support request. |
| 28 | loyalty_upgrade | medium | Asking about free upgrades and expectations around upgrades. |
| 29 | airport_gate_staff | high | Complaint about gate employees ignoring standby passengers. |
| 30 | flight_disruption | high | Flight has no plane and no departure information; active disruption. |
| 31 | baggage | high | Asking for clarification about declaring a bag lost. |
| 32 | other_unclear | medium | General dissatisfaction with the brand/request; underlying issue is missing from the message. |
| 33 | seat | high | Customer cannot get seats together. |
| 34 | flight_information | medium | Issue concerns incorrect/misassigned gate information. |
| 35 | non_support | high | Simple thank-you with no actionable request. |
| 36 | non_support | high | Casual comment with no actionable support request. |
| 37 | flight_disruption | high | Multiple delays caused a missed connection and significant itinerary disruption. |
| 38 | loyalty_upgrade | high | Customer lost an upgrade because of a missed connection. |
| 39 | booking_change | medium | Gate agent could make the requested change, but it was too late. |
| 40 | flight_disruption | high | Customer was deplaned and has no new departure time or aircraft information. |
| 41 | non_support | high | Positive/casual observation about a gate agent with no support request. |
| 42 | fees_charges | high | Complaint about having to pay an additional $75 to take an earlier flight. |
| 43 | baggage | high | Customer is being forced to check a bag because the aircraft is full. |
| 44 | flight_information | low | Only provides flight numbers; insufficient context for a more specific intent. |
| 45 | airport_gate_staff | medium | Message concerns an American Airlines employee at the airport and a reported interaction. |
| 46 | non_support | high | Thank-you message with no actionable support request. |
| 47 | flight_information | low | Message is context-dependent and mainly provides advice/commentary without a clear request. |
| 48 | flight_information | low | Provides flight/connection details but the actual request is missing. |
| 49 | non_support | high | Casual reaction with no actionable support request. |
| 50 | contact_support | high | Customer was directed to use an online form after being forwarded by customer service. |

In [ ]:
# Taxonomy Freeze

## Final Intent Taxonomy

The taxonomy was developed through an initial discovery sample followed by
unseen validation examples. The final taxonomy contains 15 categories.

| Intent | Definition |
|---|---|
| `flight_disruption` | Delays, cancellations, missed connections, deplaning, or other active flight disruptions. |
| `baggage` | Checked/carry-on baggage, lost bags, baggage fees, or baggage handling issues. |
| `booking_change` | Changing, cancelling, rebooking, or modifying an existing itinerary. |
| `seat` | Seat assignment, seating together, paid seats, or seat-related issues. |
| `loyalty_upgrade` | Loyalty status, upgrades, priority benefits, or upgrade-related issues. |
| `fees_charges` | Complaints or questions primarily about fees, charges, or additional costs. |
| `refund_compensation` | Refunds, compensation, vouchers, or reimbursement requests. |
| `flight_information` | Requests or comments primarily seeking flight, gate, schedule, or connection information. |
| `airport_gate_staff` | Issues involving airport/gate operations or employee/staff behavior. |
| `onboard_aircraft` | Issues concerning the aircraft or onboard experience. |
| `contact_support` | Attempts to contact customer support or questions about support channels. |
| `check_in` | Online/airport check-in problems or questions. |
| `follow_up` | A continuation of an existing support conversation without enough information to establish a new primary intent. |
| `non_support` | Thanks, reactions, casual comments, or other messages with no actionable support request. |
| `other_unclear` | A potentially support-related message that cannot be reliably assigned to another intent from the available context. |

## Labeling Rules

- Assign the **primary actionable intent**.
- Emotional tone does not determine the intent.
- For multiple issues, choose the customer's main actionable goal.
- Use `other_unclear` when the available message lacks enough context.
- Use `non_support` for messages with no actionable support request.
- Do not infer an intent that is not supported by the message.

In [ ]:
# Taxonomy v2 — AmericanAir

Based on the initial discovery sample and the first 25-example validation sample, I revised the candidate taxonomy.

The taxonomy is still provisional and will be tested on another unseen sample before being frozen.

## Proposed intents

### 1. flight_disruption
Issues involving delays, cancellations, missed connections, crew/operational disruptions, or other disruptions affecting the customer's flight.

### 2. baggage
Issues involving lost, delayed, damaged, checked, or incorrectly charged baggage.

### 3. booking_change
Requests to change, cancel, reschedule, or otherwise modify an existing flight booking.

### 4. seat
Issues involving seat assignment, paid seats, exit-row seats, seating arrangements, or seat availability.

### 5. loyalty_upgrade
Issues involving upgrades, loyalty status, priority boarding, or loyalty benefits.

### 6. fees_charges
Questions or disputes primarily concerning fees, charges, or penalties.

### 7. refund_compensation
Requests for refunds, reimbursement, compensation, vouchers, or goodwill compensation.

### 8. flight_information
Requests for flight information, schedules, routes, or status when the customer is not primarily reporting a disruption.

### 9. airport_gate_staff
Issues primarily involving airport staff, gate agents, boarding staff, or airport customer-service personnel.

### 10. onboard_aircraft
Issues involving the aircraft, cabin environment, onboard equipment, facilities, or onboard experience.

### 11. contact_support
Requests for phone numbers, contact information, or assistance reaching customer support.

### 12. check_in
Issues involving online check-in, check-in technical problems, or inability to complete the check-in process.

### 13. follow_up
A continuation of an existing support interaction without a clearly stated new support problem.

### 14. non_support
Messages that do not contain a new support request, such as thanks, praise, acknowledgements, or social reactions.

### 15. other_unclear
Messages where the customer's support goal cannot be reliably determined from the available context, or where the topic does not fit the current taxonomy.

---

## Categories not yet promoted to dedicated intents

The first validation sample contained isolated examples involving:

- Trip insurance
- Promotions
- Account/name information
- Transportation assistance

These are not yet promoted to dedicated intents because one or a few examples are insufficient evidence that they represent frequent enough support categories.

They will remain under `other_unclear` during the next validation round unless the broader sample shows that they occur frequently.

---

## Primary-intent rule

When multiple issues occur in one message, assign the intent corresponding to the customer's primary actionable goal.

Do not assign multiple domain intents.

If no meaningful support goal is present, use `non_support`, `follow_up`, or `other_unclear` as appropriate.

---

## Important ambiguity boundaries

### flight_disruption vs. flight_information

Use `flight_disruption` when something has gone wrong or is actively disrupting the customer's travel.

Use `flight_information` when the customer is primarily requesting information without reporting a disruption.

### fees_charges vs. refund_compensation

Use `fees_charges` when the main issue is a fee or charge.

Use `refund_compensation` when the customer is primarily asking to receive money, reimbursement, vouchers, or compensation.

### flight_disruption vs. airport_gate_staff

Use `airport_gate_staff` when the main problem is the behavior or action of airport/gate personnel.

Use `flight_disruption` when the main problem is the operational disruption itself.

### seat vs. loyalty_upgrade

Use `seat` for a specific seat assignment or paid-seat problem.

Use `loyalty_upgrade` for upgrades, status, priority boarding, or loyalty benefits.

---

## Taxonomy status

This taxonomy is provisional.

It will be tested against another unseen sample before being frozen for Golden Set construction.

In [56]:
taxonomy_validation_2 = american_messages[
    ~american_messages["customer_tweet_id"].isin(discovery_ids)
].iloc[25:].sample(
    n=50,
    random_state=456
).reset_index(drop=True)

In [57]:
taxonomy_validation_2.shape

(50, 4)

In [58]:
for i, message in enumerate(
    taxonomy_validation_2["customer_message"].iloc[:25],
    start=1
):
    print(f"\n{i}. {message}")

1. @AmericanAir So i am stuck? I checked in within the half and hour and already group 6? Crazy. Even @SouthwestAir isn’t that bad

2. @AmericanAir Well, @AmericanAir, your staff had no answers for 3 hours as to why my flight was delayed, so I'm not sure you did your best this time.

3. @AmericanAir that's ridiculous. I've had it where it's "bigger" than this flight and MEVER had an issue. You've got an extra few inches

4. @AmericanAir wow! A1 customer service with that quick response👌🏻

5. @AmericanAir then a 3 1/2 hr delay in CLT   Nov 5, we were told "the plane wad broken" &amp; somehow we had no flight crew, how does this happen on 1 trip

6. @AmericanAir I just don't understand why there were 100s of umbrellas and we couldn't use one. Why employees had them staring as I walked in rain. My bag was with me. An umbrella would've kept it dry.

7. @AmericanAir Are you offering rebooking? My itinerary is through expedia so my itinerary is part one company and part american airlines. I want to know if I should cancel the whole thing or if American plans on assisting us.

8. @AmericanAir Great when can I expect my full refund

9. @AmericanAir Apologies don't fix anything

10. @AmericanAir @816860 What does this public, written "assurance" entail?

11. @AmericanAir And thank you for the warm cookies and the free wine! 😍😍😍

12. @AmericanAir Who can I contact directly? I have photographic evidence and would like to get this resolved.

13. @AmericanAir @188391 It's better to respond in DM, so when treating customers like trash, it isn't public.

Update us on how bad AA is when they "help" you

14. @AmericanAir Thanks but I’d rather have reduced and shortened delays with your airline. I’m on my 70th segment this year between 3 airlines. And I’m pretty sure most if not all, of my delays are with AA. Including the horrendously long time it takes at DFW to get my bag.

15. @AmericanAir I see, well thank you for the explanation. Is there another flight earlier from my delayed flight I can possible join?

16. @AmericanAir Thank you for getting back to me. No. We were pointed to no such team. This is CUN airport.

17. @AmericanAir How do you fix this? This was important to me. And obviously not you. https://t.co/PbDijQiWlz

18. @AmericanAir all this back and forth w/o resolving anything.. the actual issue is about gate agents being rude and ridiculously unhelpful on a holiday when the travel stress levels is peak high

19. @AmericanAir Can't possibly be healthy for your employees. https://t.co/L2JWDm4r4m

20. @AmericanAir Free drinks 🍸 on the maintainence crew????

21. @AmericanAir Met you in DM, please answer

22. @AmericanAir There are no humans at American! Crazy

23. @AmericanAir Yes. The point I keep having to repeat is that your "change charge" at such a high *flat rate* is predatory. A percentage would work better.

24. @AmericanAir #TY for the reply - I had to catch a ferry to #STT and caught a flight on @Delta. I met people in #STT who had been on standby for days #NotEasy. Nice if all airlines could add more flights - Some people are stuck. I almost went to St. Kitts to get a flight on @AmericanAir

25. @AmericanAir @JetBlue doesn’t have this problem

In [60]:
for i, message in enumerate(
    taxonomy_validation_2["customer_message"].iloc[25:50],
    start=26
):
    print(f"\n{i}. {message}")

26. @AmericanAir @192538 Actually at high altitude food tastes worse than *ANYWHERE

https://t.co/QM4EmtSRaE

But how could you, an airline, know? 😂

27. @AmericanAir One thing you can do though is let your web dev team know that when booking, there are two spaces instead of one between "refund" and "if". https://t.co/VWQV3UkOxx

28. @AmericanAir We don't have any as this is our first big trip!! We heard free upgrades were a thing out of the kindness of your hearts ;)

29. @AmericanAir Not good when 4 AA employees at the gate are discussing their rollover statuses, while 2 stand-by pax for the plane at the gate are ignored

30. @AmericanAir And now your gate agent has left. So we don’t have anyone to even ask what’s going on. Still no plane. Still no answers. You guys are the worst airline. I don’t even know what you could do to make me feel better.

31. @AmericanAir Sent DM yesterday but will again- thx! Would appreciate some clarification on declaring bag lost.

32. @AmericanAir I’m seriously questioning my loyalty to your brand right about now. I don’t think my request was out of line.

33. @AmericanAir "20-30" seats open and not able to sit together. Just awful.

34. @AmericanAir It is. The gate it was set up to was the gate for the following flight to the same destination.

35. @AmericanAir @120944 Thank you

36. @AmericanAir Also they are hilarious

37. @AmericanAir I am trying to get to GRU, but this morning was my second delay and again lost my connection... new ETA is tomorrow morning only...

38. @AmericanAir Yeah. We lost the upgrade on the connection we missed, a central reason we planned so far in advance.

39. @AmericanAir Nope. Gate agent could add me. But way too late.

40. @AmericanAir Now we have had to deplane with no information on a new departure time or plane. Really #goingforgreat

41. @AmericanAir The signing/dancing gate agent at C4 is playing Neil Diamond and Journey for everyone. So that's happening. #ctl #aa1918.

42. @AmericanAir YEA OK! You guys would much rather a seat go empty then let a customer get on a earlier flight without paying a extra 75 dollars.

43. @AmericanAir And now you force me to check my bag because other plane is full. Great experience @AmericanAir - NOT!!! Some things never change

44. @AmericanAir 1850 then connecting 3381

45. @AmericanAir The AA employee at the Miami Airport that used my phone to call my husband unfortunately didn't say his name. I emailed you the full story.

46. @AmericanAir @117157 @118818 thanks so much for the help and trying to get AA to make our anneversary special the above tweet was sarcasm.

47. @AmericanAir @691562 @691562 should plan better next time and not show up 9 minutes before your flight departs.

48. @AmericanAir 2059. A few weeks ago the same thing happened on arrival in ORD from DUB - not on the list for a connection to DFW

49. @AmericanAir @335127 NO U DIDNT HAHAHAHAHH IM DYING

50. @AmericanAir  I did. They forwarded me to go online and fill out a form. Probably the underlying issue in the customer service.

In [63]:
american_messages.columns

Index(['customer_tweet_id', 'customer_message', 'brand_response',
       'message_length'],
      dtype='str')

In [64]:
used_ids = set(discovery_sample["customer_tweet_id"])
used_ids.update(taxonomy_validation["customer_tweet_id"])
used_ids.update(taxonomy_validation_2["customer_tweet_id"])

# Candidate pool that has never been used in taxonomy development
golden_pool = american_messages[
    ~american_messages["customer_tweet_id"].isin(used_ids)
].copy()

print("Total AmericanAir messages:", len(american_messages))
print("Used during taxonomy development:", len(used_ids))
print("Available for Golden Set:", len(golden_pool))

Total AmericanAir messages: 18045
Used during taxonomy development: 350
Available for Golden Set: 17695

In [66]:
golden_pool = golden_pool.copy()

# Create message-length groups
golden_pool["length_group"] = pd.qcut(
    golden_pool["customer_message"].str.len(),
    q=4,
    labels=["short", "medium", "long", "very_long"],
    duplicates="drop"
)

# Sample proportionally across message-length groups
golden_set = (
    golden_pool
    .groupby("length_group", observed=True, group_keys=False)
    .apply(
        lambda x: x.sample(
            n=round(200 * len(x) / len(golden_pool)),
            random_state=42
        )
    )
)

# Ensure exactly 200 examples
if len(golden_set) > 200:
    golden_set = golden_set.sample(n=200, random_state=42)

elif len(golden_set) < 200:
    remaining = golden_pool.loc[
        ~golden_pool.index.isin(golden_set.index)
    ]

    golden_set = pd.concat([
        golden_set,
        remaining.sample(
            n=200 - len(golden_set),
            random_state=42
        )
    ])

# Recreate length_group because groupby/apply may remove it
golden_set["length_group"] = pd.qcut(
    golden_set["customer_message"].str.len(),
    q=4,
    labels=["short", "medium", "long", "very_long"],
    duplicates="drop"
)

print("Golden Set size:", len(golden_set))
print("\nLength distribution:")
print(golden_set["length_group"].value_counts())print("Discovery overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(discovery_sample["customer_tweet_id"])))

print("V1 validation overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(taxonomy_validation["customer_tweet_id"])))

print("V2 validation overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(taxonomy_validation_2["customer_tweet_id"])))

Golden Set size: 200

Length distribution:
length_group
short        51
long         50
very_long    50
medium       49
Name: count, dtype: int64

In [67]:
golden_pool = golden_pool.copy()

# Create message-length groups
golden_pool["length_group"] = pd.qcut(
    golden_pool["customer_message"].str.len(),
    q=4,
    labels=["short", "medium", "long", "very_long"],
    duplicates="drop"
)

# Sample proportionally across message-length groups
golden_set = (
    golden_pool
    .groupby("length_group", observed=True, group_keys=False)
    .apply(
        lambda x: x.sample(
            n=round(200 * len(x) / len(golden_pool)),
            random_state=42
        )
    )
)

# Ensure exactly 200 examples
if len(golden_set) > 200:
    golden_set = golden_set.sample(n=200, random_state=42)

elif len(golden_set) < 200:
    remaining = golden_pool.loc[
        ~golden_pool.index.isin(golden_set.index)
    ]

    golden_set = pd.concat([
        golden_set,
        remaining.sample(
            n=200 - len(golden_set),
            random_state=42
        )
    ])

# Recreate length_group because groupby/apply may remove it
golden_set["length_group"] = pd.qcut(
    golden_set["customer_message"].str.len(),
    q=4,
    labels=["short", "medium", "long", "very_long"],
    duplicates="drop"
)

print("Golden Set size:", len(golden_set))
print("\nLength distribution:")
print(golden_set["length_group"].value_counts())

Golden Set size: 200

Length distribution:
length_group
short        51
long         50
very_long    50
medium       49
Name: count, dtype: int64

In [68]:
print("Discovery overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(discovery_sample["customer_tweet_id"])))

print("V1 validation overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(taxonomy_validation["customer_tweet_id"])))

print("V2 validation overlap:",
      len(set(golden_set["customer_tweet_id"]) &
          set(taxonomy_validation_2["customer_tweet_id"])))

Discovery overlap: 0
V1 validation overlap: 0
V2 validation overlap: 0

In [70]:
from pathlib import Path

Path("evaluation").mkdir(parents=True, exist_ok=True)

golden_set.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved:", len(golden_set), "examples")

Saved: 200 examples

In [71]:
golden_set["intent"] = ""
golden_set["confidence"] = ""
golden_set["notes"] = ""

# Keep only the columns needed for annotation
golden_annotation = golden_set[
    [
        "customer_tweet_id",
        "customer_message",
        "intent",
        "confidence",
        "notes"
    ]
].copy()

# Save annotation template
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Annotation template created:", len(golden_annotation), "examples")

Annotation template created: 200 examples

In [72]:
golden_annotation.head(10)

,customer_tweet_id,customer_message,intent,confidence,notes
375181,1952986,@AmericanAir can't wait to switch to a @Delta ...,,,
109288,548815,@AmericanAir Must be a long walk.........,,,
431926,2308158,@AmericanAir Thanks! Will DM you,,,
300255,1528201,@AmericanAir ALready did and no help. very dec...,,,
526792,2813114,@AmericanAir Thank you!! Hoping it works out.,,,
211914,1075780,@AmericanAir Of course no response. Because yo...,,,
151899,775494,@AmericanAir Please DM ME,,,
391493,2075103,@AmericanAir DMing now. Thanks.,,,
114804,578855,@AmericanAir Sounds great. Thank you!,,,
267702,1358740,@AmericanAir 3114,,,

In [73]:
VALID_INTENTS = {
    "flight_disruption",
    "baggage",
    "booking_change",
    "seat",
    "loyalty_upgrade",
    "fees_charges",
    "refund_compensation",
    "flight_information",
    "airport_gate_staff",
    "onboard_aircraft",
    "contact_support",
    "check_in",
    "follow_up",
    "non_support",
    "other_unclear",
}

VALID_CONFIDENCE = {"high", "medium", "low"}

print("Valid intents:", len(VALID_INTENTS))
print("Valid confidence levels:", VALID_CONFIDENCE)

Valid intents: 15
Valid confidence levels: {'low', 'medium', 'high'}

In [74]:
golden_annotation.iloc[0:25][
    ["customer_tweet_id", "customer_message"]
]

       customer_tweet_id                                   customer_message
375181           1952986  @AmericanAir can't wait to switch to a @Delta ...
109288            548815          @AmericanAir Must be a long walk.........
431926           2308158                   @AmericanAir Thanks! Will DM you
300255           1528201  @AmericanAir ALready did and no help. very dec...
526792           2813114      @AmericanAir Thank you!! Hoping it works out.
211914           1075780  @AmericanAir Of course no response. Because yo...
151899            775494                          @AmericanAir Please DM ME
391493           2075103                    @AmericanAir DMing now. Thanks.
114804            578855              @AmericanAir Sounds great. Thank you!
267702           1358740                                  @AmericanAir 3114
161367            821839              @AmericanAir Possible cancellation???
552341           2943930  @AmericanAir Same story different day. 2 weeks...
213657           1084569        @AmericanAir I appreciate that @AmericanAir
328662           1671871     @AmericanAir @508852 Thats soo cumming :) :P 😗
35658             185681              @AmericanAir  https://t.co/KSQSEKWRff
217209           1103882   @AmericanAir All is well! Fixed it with an agent
241082           1224737          @AmericanAir Isn’t that convenient? #lame
408349           2174392                                  @AmericanAir WA 🌎
389204           2057543                   @AmericanAir Thanks - DM'ing now
507608           2710227            @AmericanAir AA 2767 out of MIA to EWR.
505713           2699896       @AmericanAir @758493 Have a safe flight back
352404           1803430                           @AmericanAir Flight 1904
196202            994691                         @AmericanAir Yes I did ...
452617           2417180  @AmericanAir Thank you for keeping us safe in ...
130471            664494  @AmericanAir I've just sent you a copy of your...

In [75]:
pd.set_option("display.max_colwidth", None)

golden_annotation.iloc[0:25][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
375181,1952986,@AmericanAir can't wait to switch to a @Delta member.
109288,548815,@AmericanAir Must be a long walk.........
431926,2308158,@AmericanAir Thanks! Will DM you
300255,1528201,@AmericanAir ALready did and no help. very deceitful practices
526792,2813114,@AmericanAir Thank you!! Hoping it works out.
211914,1075780,@AmericanAir Of course no response. Because you don’t care
151899,775494,@AmericanAir Please DM ME
391493,2075103,@AmericanAir DMing now. Thanks.
114804,578855,@AmericanAir Sounds great. Thank you!
267702,1358740,@AmericanAir 3114
161367,821839,@AmericanAir Possible cancellation???
552341,2943930,@AmericanAir Same story different day. 2 weeks later...
213657,1084569,@AmericanAir I appreciate that @AmericanAir
328662,1671871,@AmericanAir @508852 Thats soo cumming :) :P 😗
35658,185681,@AmericanAir https://t.co/KSQSEKWRff
217209,1103882,@AmericanAir All is well! Fixed it with an agent
241082,1224737,@AmericanAir Isn’t that convenient? #lame
408349,2174392,@AmericanAir WA 🌎
389204,2057543,@AmericanAir Thanks - DM'ing now
507608,2710227,@AmericanAir AA 2767 out of MIA to EWR.
505713,2699896,@AmericanAir @758493 Have a safe flight back
352404,1803430,@AmericanAir Flight 1904
196202,994691,@AmericanAir Yes I did ...
452617,2417180,@AmericanAir Thank you for keeping us safe in the air.
130471,664494,@AmericanAir I've just sent you a copy of your message

In [76]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 1–25")

Saved 1–25

In [77]:
golden_annotation.iloc[25:50][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
488304,106586,@AmericanAir Yeah...not me though. https://t.co/V6fSMyqDaW
237280,1206247,@AmericanAir DM sent.
62513,312228,@AmericanAir Appreciate what?
195470,991322,@AmericanAir Thank you. I have done that
533145,2844768,@AmericanAir Correct.
277876,1411117,@AmericanAir That doesn't seem right
298810,1520560,@AmericanAir It's all such a racket.
446295,2384389,"@AmericanAir Ok, so I've DM'd you, but no reply."
547586,2919509,@AmericanAir This is the 4th time this has happened to me!
5933,32540,@AmericanAir Sent you the DM with the record locator
165451,842047,@AmericanAir I sent it to you via DM. Thank you.
39236,205373,@AmericanAir I have sent u the details via DM
402993,2143131,@AmericanAir Well you’re not doing enough
505046,2696359,@AmericanAir To little to late after you made our baby starve
548882,2926053,@AmericanAir AA1566 this a.m. Flight crew was amazing!
514813,2747726,@AmericanAir Anyone I can call to ask them to hold it?
544567,2902978,"@AmericanAir Sorry, what do you need??"
170839,867726,@AmericanAir You are so right. Life is so full of #AAdventures
351026,786625,"@AmericanAir Thank you, will do!"
471043,2514506,@AmericanAir Now our seats aren't together.
338929,1728135,@AmericanAir Flight is 100% full.
357218,1836827,@AmericanAir Nope all set cancelled flight getting full refund
312505,1592568,@AmericanAir 125598130514
277863,1411083,@AmericanAir Or at least get some beverages handed out
344476,1756727,@AmericanAir I know !!

In [78]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 26–50")

Saved 26–50

In [79]:
golden_annotation.iloc[50:75][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
225756,1146874,"@AmericanAir @163646 And again, they don’t get it..."
35660,185701,@AmericanAir thanks for the quick response! Hopefully it's up in the air soon! 👍🏼
178687,907593,@AmericanAir AA0098. Also an update on the socks/ blanket situation would be nice 👍
450398,2016408,@AmericanAir @116147 Preferred airline of American Nazi's. https://t.co/79nps14moj
191108,970703,@AmericanAir The landing in Portland that is. Pulling up 100 ft above the flight deck? Who does that?
307172,1565423,@AmericanAir No it doesn’t. I’ve even called your slightly english speaking hotline and they wouldn’t do it.
137618,701891,"@AmericanAir Yep, meant 5608. This is what 4.5 hours in an airport on Thanksgiving does to a person."
485235,2591114,"@AmericanAir This was an AA error, don’t you take responsibility to it?"
440683,2354076,@AmericanAir A refund of the ridiculous $600 changeover fee would be nice.
486067,2595722,@AmericanAir @186585 I will never fly on any other airline again.
208827,1059065,@AmericanAir I’m still in the middle of the worst travel day ever!! No end in sight. Thx for nothing
81399,407623,"@AmericanAir @212165 Wait, are you actually seeing SYD-LAX-DCA Award \nflights?!?!?"
64409,320711,@AmericanAir I have 5 upcoming flights in this month alone. I'm tweeting every delay to prove my point 💁
507453,2709410,@AmericanAir at what point are you going to offer us a refund or different flight?
508346,2714322,@AmericanAir If you don’t refund my money this is my last AA flight.
238233,1210848,@AmericanAir I am not happy 😡total bs and system very slow this am not happy client need someone to call me
470057,2509196,@AmericanAir The inbound flights arrival time just keeps slipping..... https://t.co/6JaLViSmsZ
178192,904832,@AmericanAir Thanks! Doesn't look like I am keeping that status this year :(
78653,391329,@AmericanAir The total cost came to be $250 for the same flight! This is ridiculous!!!
535309,2856026,@AmericanAir 656. Why? How many planes are you having toilet problems on?
3090,18785,@AmericanAir Flight 254 from Maui to LAX. First class (seating and service).
449564,2400710,@AmericanAir But food??? They stop and get food... what if I was late because of their same stop??
67110,333714,@AmericanAir @158394 Classic #AAteam \nHope it gets resolved Chris
555447,2960800,@AmericanAir Did it depart? You responded 15 min after that time
557917,2974048,@AmericanAir @820223 Letting a navy seal into any lounge may be a bad decision. 😘😉

In [80]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 51–75")

Saved 51–75

In [81]:
golden_annotation.iloc[75:100][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
352249,1802248,@AmericanAir I don't pay the car dealership for my insurance you fucking twat.
225754,1146872,@AmericanAir @163646 It’s not about a singular flight. It’s a systematic issue.
32594,171295,@AmericanAir You don't need to check the status the flight been delayed and I been known fuck off
32855,172593,@AmericanAir Thank you I will let you know when I book everything and stuff I like the Airbuses
35444,184256,@AmericanAir Fantastic! Thanks! And it looks like my seat is selected now!
400270,2127779,@AmericanAir Last one on the plane. Never been so happy to see seat 1A.
434429,2321087,@AmericanAir Alright. Fingers crossed. Happy Monday to you too.
291861,1484538,@AmericanAir In DFW then re-check in the morning. Now you guys are holding my bags here DFW till tomorrow.
87574,258067,@AmericanAir Yeh American. It's gonna take real action not videos to improve perceptions of your service
220115,1118791,"@AmericanAir I didn't write it, A very angry customer did. I myself had a nice flight. Thanks"
276611,1404726,@AmericanAir And if it's not ... There will be plenty of Bourbon in Louisville to soothe the pain :)
65776,327141,"@AmericanAir Well, you didn't on October 5th. That's when I traveled to SJU."
533148,2844774,@AmericanAir ABSOLUTELY I did. He heard it as I ran past him. 100%
321165,1631934,"@AmericanAir It’s one of the weird travel things I get the most anxious about, so THANK YOU 🙏🏻🙏🏻🙏🏻"
9466,52410,@AmericanAir Yes that would work. I am traveling with one other person. How should we go about this???
335724,1712175,@AmericanAir So I'm flying tomorrow night first class LAX to Miami. What can I expect?
230783,1172331,@AmericanAir Who can access them? Please investigate and advise.
346402,1767092,@AmericanAir An hour late and we are ALL sitting on the plane waiting
178695,907638,@AmericanAir I called and they were able to resolve my issue in a respectful time and manner
175984,893206,@AmericanAir Thank you for your response! Where is DM located at DFW?
287503,1460835,@AmericanAir @americanair - why not just tell me you updated crew from economy to first.
168160,854918,@AmericanAir Thank you so much! Love AA! Look forward to flying with you again near the future!
470306,2510745,@AmericanAir Your apologies don't mean anything if you never get better.
233469,1185979,@AmericanAir But I have thousands of dollars in change fees on my Europe flights.
368257,1907989,"@AmericanAir There are none. This flight is full and I paid extra for a,window seat so I could sleep"

In [82]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 76–100")

Saved 76–100

In [83]:
golden_annotation.iloc[100:125][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
51418,259579,"@AmericanAir That doesn't make me feel rewarded for my loyalty, sad. @13309 what boarding group does Delta reward your status with?"
411374,2191848,"@AmericanAir Every single time I fly with @AmericanAir it’s far from “exceptional”, each time Its the same excuses, never ownership"
491013,2621397,@AmericanAir Missed first night of business and now day two. #allyou #peopleneedtogetthere #youaresorry #lasttime
139763,713447,@AmericanAir You inconvinced me and LIED and I'm looking for credit back and file complaint against employees.
197816,1002991,@AmericanAir Not availability problem. Have to make a last minute change and now I have to forfeit all the miles I spent. Ridiculous.
52717,265716,@AmericanAir That’s nice. Thank you. There are plenty of restaurants already at the airport. But we need some where sit.
309433,1576609,@AmericanAir It's just upsetting that all airlines don't take responsibility for their s.n.a.f.u.s and just shaft the customer. It's childish 😕😑
398362,2116425,"@AmericanAir @AmericanAir No, this was at security. Not at boarding. You're not holding a security priority lane any longer."
408354,2174435,@AmericanAir There was definitely a change charge to the tune of 70% of original cost. I guess the 3 hour delay was free of charge. Thanks again.
504020,2691138,@AmericanAir We've been on this plane since 6a eastern time…on a flight that usually takes 4.5 hours…with so so service…terrible
75466,376868,@AmericanAir give your websites some type of basic function to select your own flights for multi city pairings
210275,1067344,"@AmericanAir Are you kidding me. Your website, app, and service kiosk wouldn't let us check in when we were supposed to. You guys suck."
362775,1868718,@AmericanAir Oh look at that. They were all at the tying carousel and no one told us. You guys suck. https://t.co/884GycFUA8
75280,375910,@AmericanAir Will do. I do hope this gets resolved ASAP because otherwise this work trip for @18019 may be ruined.
197703,1002423,@AmericanAir Just arrived at the gate. That fight to ORD is delayed as well and since we aren't holding planes today I'll work to book another one.
168976,858641,@AmericanAir Then she said I had to check it as soon as I walked 1 minute from the plane to boarding gate . They said flight closed
384923,1850123,"@AmericanAir I fly with you often but because my ticket is the ""no change"" flight they wouldn't fix. The end result would have been the same"
297890,1515541,@AmericanAir Couldn't get out of my sales meeting as early as I had hoped ... such is life ... thanks for your help!
489339,1787519,@AmericanAir Now I have to consolidate and now my bag is too wide to fit under the seat. INCONVENIENT when traveling.
427647,2284896,@AmericanAir You had the chance and refused to be reasonable. Looking forward to sharing my friends' @AmericanAir horror stories.
441219,2357007,"@AmericanAir Yes, if you consider “Baggage status: File xxxxxxx has been closed” actually tracking anything. Or even informative."
268628,1365064,@AmericanAir these situations need better communication. We were told to go to a diff gate and now back w no corrective announcement
374099,1946697,"@AmericanAir Its a bit late for that given I fly today. I want free bags applied to a AA Advantage 4T1BW36, confirmation DHHSOR. #FAA #FTC"
446213,2383973,"@AmericanAir #joke. How are you ""helping"" your top tier passengers? #rude employees #terrible #passengerExperience NO #CustomerLoyalty."
312509,1592562,"@AmericanAir Dealing w/ SFO mgr: Mark Lam, who will not tell me how to reach the CR agent who he earlier said does not exist"

In [84]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 101–125")

Saved 101–125

In [85]:
golden_annotation.iloc[125:150][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
445060,2378413,@AmericanAir Ali Khatab finally did the right thing. Thx to him. No thanks to AA for resisting and not doing the right thing initially.
353647,1812226,"@AmericanAir How exactly? Please elaborate? If today’s treatment was anything to go by, I don’t really want your team’s ‘great care’."
58325,291926,@AmericanAir Yeah in Wednesday it was the same way until the time of departure! You’ll forgive me if my confidence is at an all time low!
213556,1084105,@AmericanAir Also our @46987 is flying @americanair this week as they head into New Orleans! https://t.co/a0qK44K10s
182352,925989,@AmericanAir That is a stupid response - that is the number I have called and getting disconnected from- why don’t you read the original tweet
299907,1526338,@AmericanAir Yes but your website timed out. Then increased the price. I know about dynamic pricing. Glitch then increase fare is why I am upset.
398847,2119599,"@AmericanAir I’m not a million miler and am just a small fish in the frequent flier pool, but I️ do try to stay loyal to AA..."
156634,798521,"@AmericanAir Missed my connection because of your constant delays, was lied to about airport shuttle transportation to my hotel."
190555,968348,@AmericanAir She doesn't have twitter but her name is Emily Hinckley and if I were American Airlines I would be calling her and offering an apology
373386,1942622,"@AmericanAir We had to purchase a totally new flight, would love to connect on a refund. What do you mean by locator?"
283459,1439236,@AmericanAir I wish I had but did not. But she was the blond lady with her hair in an up-do at front desk in arrivals lounge Term 3
559833,2987780,@AmericanAir Thanks. Looks like a lot of mistakes in @116125 at this time. Same as LH 410. isn’t diverted to LGA
536804,2864245,@AmericanAir Define a few. They haven't started boarding yet so 6:35 or a few minutes is not a valid estimate
139767,713475,@AmericanAir If my bag does not appear by any means you guys would need to make me a refund of all my articles that wore inside my bag!
309177,1566224,"@AmericanAir very delightful return trip ~ multiple people needing special assistance. The team was quick, efficient and very courteous. AA+"
248191,1261508,@AmericanAir I worked with them. They were very helpful and got me rebooked into Nashville. All four agents at DCA 35X were fast!
367515,1187827,"@AmericanAir I could go on and on, but this was the most annoying of about 10 issues. I will never fly with you again."
472434,2522664,@AmericanAir understood! Thank you! Trying to help a friend of mine who has no Twitter understand this new world. Thanks again I will (1/2)
186115,945069,@AmericanAir Let me get this straight I have to DM you when my flight is complete? Shouldn't you be DM'ing me ? Who the hell taught y'all CS?
257182,1306894,"@AmericanAir Since 5pm we've had a dozen flight times from 8 to 12, back and forth. Different times on different screens. Horrendous communication"
318364,1618120,@AmericanAir I tried everything and it’s now $300. I clicked book right after I saw it and it went away. How is that possible within minutes?
348327,1778214,@AmericanAir You have the best #employees ! Thank you @AmericanAir ! These two are real gems. #superstars #mademesmile
30711,162340,"@AmericanAir So - not likely that AA would book a pax with that tight a connection, but the replacement F/A is ok?"
111746,562499,@AmericanAir AA3202 has been delayed 4-times! We’ve been advised every hour another 30-60 mins. Isn’t DFW your ‘hub’?!
280940,1426545,@AmericanAir thanks @9484 i have been reunited. just need better and more comm on the ground it would go a long way to improve the experience .

In [86]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 126–150")

Saved 126–150

In [87]:
golden_annotation.iloc[150:175][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
344773,1758294,"@AmericanAir We r still sitting in boarding waiting for a plane that has been in maint. for 4 hours.This is not OK.No food,no back up plan,unsafe plane"
337444,1720438,@AmericanAir This #SSSS code comes from @AmericanAir - don't make like @120943 did the selection. It was a complete waste of my time and their resources.
515021,2748742,"@AmericanAir with not so friendly employees. I’m a patient person, but this is unacceptable. Customer service have to be a priority and a good one, because I’m paying for it and the least I expect is bad treatment."
233317,1185226,"@AmericanAir My wheels aren’t up - I gave up and now my bag is in NY and my 5:45AM flight is now $1,414 one way?! What on earth has happened to this airlines?"
22459,123525,"@AmericanAir Clearly you don't ""always"" if we are having this conversation. Just remind your folks to smile and say hello. Everyone pays good money to be here and working holidays does suck, I get it."
299183,1522524,"@AmericanAir @473126 Here is their secret -if they leave the gate, its a departure, whether you actually leave the ground or not. On @AmericanAir its usually not"
457162,2442140,"@AmericanAir You still have time, my flight is this evening. Pls pls ask FA to ""discipline"" those idiots who carry and store multiple carryons and leave others without space."
347175,1771230,@AmericanAir When I fly @SouthwestAir I get free bags and early boarding for free! Because they like my 40+ flights per year! Total BS. Some 19 yr old marketing moron....
481882,2572457,@AmericanAir @729565 @329789 unfortunately the @188323 want to give the Trump boys a private plane tax cut so it will be cheaper for @301294 to bring the slaughter home to share with his family
362371,1866630,"@AmericanAir Mobile BP worked at the gate, despite multiple refreshes, delete old BP, reboot iPhone, still won't update. At least I got in some jogging"
517242,2761028,@AmericanAir Any other bullshit copy/paste responses you wanna send additionally and not actually address the problem? Or just continue to be useless. @116450 would you do that to your passengers?
357914,1840929,"@AmericanAir The airline knew of the delay before they took off, so we could have been given a chance to exit the plane, go home, and try again next day."
428248,2288416,"@AmericanAir The 66th Miss Universe Pageant officially start only when Miss Venezuela comes to the host country so, can you tell to all Venezuelans the status of flight number AAL325? tx"
137232,699765,"@AmericanAir Though I understand that it's sometimes necessary for flights to be cancelled, our entire itinerary (and a six hour drive) was built around that direct flight."
320684,1137506,"@AmericanAir Difference between first class and economy worth the cost at all, being stuffed like sardines and even as a platinum member the perks are"
203731,1033182,"@AmericanAir Without at least an acknowledgement that a problem was found and fixed, she does not feel safe reboarding this flight. There *was* a problem"
331734,1689776,@AmericanAir Understood. But when you’re told at the gate that “this flight won’t accommodate your carry-on” is frustrating. Especially when you’ve...
557966,2974362,@AmericanAir Doesn’t beat southwest where all tickets are refundable. Shouldn’t have to pay a fee if you don’t even know for certain that you’ll have to cancel!
46457,238424,@AmericanAir Thank you @AmericanAir but Adele DeWitt had to pay for every change. Your agents don't seem to know when an airport will be open or not.
238331,1211364,"@AmericanAir @404322 Does that come with a side of extra racism and discrimination for black passengers as well? If so, I'd rather fly @116450 or @SouthwestAir"
206848,1048352,"@AmericanAir Here’s fine.\n\nAA 4540 (DCA-JFK) moved from Gate 37-&gt;42 with no announcement at 37, sms alert, or on 37’s screen.\n\nOne guess on the outcome."
449126,2398394,"@AmericanAir Yes, that does not dismiss the lack of option to pay for an alternate seat as you even mentioned previously or the negative attitude. You asked if you could help...where’s the help you offered?"
17192,96049,@AmericanAir I called. I was told there's a $200 change fee. Then the rep insisted on cancelling his reservation it appeared so rather than that seat go unused it could be re-sold despite the fact I wasn't offered a refund.
199770,1013171,"@AmericanAir Landed at 1146 am, back of plane off by 1158 am. Door to YUL flight closed at 1215 pm. Missed by 1 min along with 8 other ppl. No time to get there connecting across airport. Need better scheduling."
58853,294436,@AmericanAir AA told her MUST use the ticket by 2-18 but her nephew's wedding had to be cancelled due to storm. She has no reason to use the ticket

In [88]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 151–175")

Saved 151–175

In [89]:
golden_annotation.iloc[175:200][
    ["customer_tweet_id", "customer_message"]
]

,customer_tweet_id,customer_message
465270,1942939,@AmericanAir That's 550 in charges or 18 hours of a $30/hr employee? Just paid someone half a weeks wages and customer gets nothing but aggrivation.
39247,205425,@AmericanAir @164679 That's a new one. What circumstances make it operational? What compensation can we expect. I fly clt to ROA alot. Not happy about route.
335817,1607048,@AmericanAir It’s not the delay @AmericanAir - maint issues happen. It’s the onboard treatment. A bag of pretzels is an insult. Let’s rethink american.
208029,1054354,@AmericanAir And wait until Monday!? Thanks for your outstanding efforts! You build loyal customers by going above and beyond not by doing the bare min!!
357416,1837814,@AmericanAir Further down on website for basic economy it says 1 bag + personal item. Am I going to be charged extra if I go by what it says online?
410994,2189547,"@AmericanAir Yes, I understand band appreciate that. If it fits it fits! Just got off another flight with it! Placed it in the model. Still you are not satisfied? I have never, ever, seen this recourse from gate agents in the past! Should be better document if thus is your stance!"
491340,2622962,@AmericanAir Yes. You switched our carousel number and didn't tell anybody. All of our stuff was sitting at 10 instead of 12 for an hour for anybody to steal. Finally some enterprising person found it.
340545,1736540,@AmericanAir I have given the details to countless people and I’m not going to type it all here. Look at my complaints by using my advant number 29F5AD4
83254,417101,@AmericanAir I had to cut my honeymoon short BC of fire threatening my house &amp; I’m worried about my kids. But my loyalty to YOUR airline wasn’t rewarded
93797,468406,@AmericanAir I did but really service during this entire inconvenience has been really bad and no one can explain how it ended up in DAY when it was no where on my itinerary.
319313,1622441,@AmericanAir Right - it works in the AP too. Tracking doesn’t work when your bags get sent to baggage claim after checking in! #RF #notmyfirsttrip
231766,1177330,"@AmericanAir Nothing personal, just extortonate fare for my most recent trip, SouthWest would have been 25%, then extremely tiny plane. Couldn't fit bag"
518741,2768597,@AmericanAir You could’ve helped and refused. Your scripted response to the DM was insulting. Your #flightattendant was uncooperative and we were more than polite. #AmericanAirlines entire staff needs to go through #CustomerService training. @486 will be hearing about this. #unlawful air!
389806,2061947,"@AmericanAir If you won’t refund 100$, due to an emergency family issue, then you’ve shown your customer strategy. If frontier can refund so can you."
348932,1782445,@AmericanAir All you've done is what I already did online. How is that helpful? Everything is forms and answering machines. No one is actually helping.
375438,1954118,"@AmericanAir Yes, Firefox and Chrome. I have a chromebook, no IE but it's not a display bug, anyway. Something is wrong in your backend (several things)"
358555,1844577,@AmericanAir When I call there is no regard oh we will get back in contact with you it's draining they need to call me it's starting to get me more upset
541245,2886244,"@AmericanAir I just happened to check again, looking to see if my UPG cleared, and see an 32B seat map, and I had no seat. What's going on over there?"
219078,1113694,@AmericanAir My husband works for Fox News this is something he needs to do a story on how it’s one thing to have uncontrolled delays but another to lie
396955,2108169,"@AmericanAir I'm NOT going back to the airport. After you guys lost it, you took a day to find it and deliver it only to completely destroy the lock. Will you be paying for my gas or a taxi? What about my lost time?"
81224,406735,@AmericanAir No bueno. Wish u cared more about your customers than ur bottom line. Especially with the recent natural disasters. Doesn't hurt to help
113218,570567,@AmericanAir If I didn’t have a couple grand sunk into a non refundable ticket on @116450 Air-lies for a return flight tomorrow I’d be switching over as we speak. ☹️
478224,2552852,"@AmericanAir After having gone out of my way to fly AA, since the '60's, and to see several dozen passengers treated like garbage, I'm utterly disappointed... I miss the real American Airlines"
420783,2245113,@AmericanAir Reservations Supervisor Godfrey fixed it. Very nice. But you system for not spliting two elites on seperate reservations is very complex. Had to remove my AA number from record to make it work.
526984,2814090,"@AmericanAir I don’t understand. When I filed the report, I received a reply that I would get regular updates for 30 days. I’m w/in 30 days. So why am I now being told no updates?"

In [90]:
golden_annotation.to_csv(
    "evaluation/golden_set_annotation.csv",
    index=False
)

print("Saved 176–200")

Saved 176–200

In [91]:
VALID_INTENTS = {
    "flight_disruption",
    "baggage",
    "booking_change",
    "seat",
    "loyalty_upgrade",
    "fees_charges",
    "refund_compensation",
    "flight_information",
    "airport_gate_staff",
    "onboard_aircraft",
    "contact_support",
    "check_in",
    "follow_up",
    "non_support",
    "other_unclear",
}

VALID_CONFIDENCE = {"high", "medium", "low"}

print("Total examples:", len(golden_annotation))

print("\nMissing intents:",
      golden_annotation["intent"].isna().sum() +
      (golden_annotation["intent"].str.strip() == "").sum())

print("Missing confidence:",
      golden_annotation["confidence"].isna().sum() +
      (golden_annotation["confidence"].str.strip() == "").sum())

invalid_intents = set(golden_annotation["intent"].dropna()) - VALID_INTENTS
invalid_confidence = set(golden_annotation["confidence"].dropna()) - VALID_CONFIDENCE

print("\nInvalid intents:", invalid_intents)
print("Invalid confidence:", invalid_confidence)

print("\nIntent distribution:")
print(golden_annotation["intent"].value_counts())

Total examples: 200

Missing intents: 200
Missing confidence: 200

Invalid intents: {''}
Invalid confidence: {''}

Intent distribution:
intent
    200
Name: count, dtype: int64

In [3]:
import pandas as pd

df = pd.read_csv("evaluation/golden_set_annotation.csv")

df.to_excel(
    "evaluation/golden_set_annotation.xlsx",
    index=False
)

print("Created Excel file")

Created Excel file

In [4]:
golden_annotation = pd.read_csv(
    "evaluation/golden_set_annotation.csv"
)

print("Rows:", len(golden_annotation))

Rows: 200

In [5]:
VALID_INTENTS = {
    "flight_disruption", "baggage", "booking_change", "seat",
    "loyalty_upgrade", "fees_charges", "refund_compensation",
    "flight_information", "airport_gate_staff", "onboard_aircraft",
    "contact_support", "check_in", "follow_up", "non_support",
    "other_unclear"
}

VALID_CONFIDENCE = {"high", "medium", "low"}

print("Rows:", len(golden_annotation))

print("Missing intents:",
      golden_annotation["intent"].fillna("").str.strip().eq("").sum())

print("Missing confidence:",
      golden_annotation["confidence"].fillna("").str.strip().eq("").sum())

print("Invalid intents:",
      set(golden_annotation["intent"].dropna()) - VALID_INTENTS)

print("Invalid confidence:",
      set(golden_annotation["confidence"].dropna()) - VALID_CONFIDENCE)

print("\nIntent distribution:")
print(golden_annotation["intent"].value_counts())

Rows: 200
Missing intents: 0
Missing confidence: 0
Invalid intents: set()
Invalid confidence: set()

Intent distribution:
intent
non_support            51
follow_up              33
flight_disruption      21
fees_charges           11
baggage                11
contact_support        10
airport_gate_staff     10
refund_compensation     9
flight_information      8
booking_change          8
other_unclear           7
seat                    6
onboard_aircraft        6
loyalty_upgrade         6
check_in                3
Name: count, dtype: int64